<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>NFMWorld.Platform.SDL3</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SDL3-CS" Version="3.4.14.1" />
        <PackageReference Include="SDL3-CS.Windows" Version="3.4.14.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NFMWorld.Library\NFMWorld.Library.csproj" />
    </ItemGroup>

</Project>
