<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Include="..\FNA\src\BoundingBox.cs">
        <Link>BoundingBox.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\BoundingFrustum.cs">
        <Link>BoundingFrustum.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\BoundingSphere.cs">
        <Link>BoundingSphere.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Color.cs">
        <Link>Color.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\ContainmentType.cs">
        <Link>ContainmentType.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\BoundingBoxConverter.cs">
        <Link>Design\BoundingBoxConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\BoundingSphereConverter.cs">
        <Link>Design\BoundingSphereConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\ColorConverter.cs">
        <Link>Design\ColorConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\MathTypeConverter.cs">
        <Link>Design\MathTypeConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\MatrixConverter.cs">
        <Link>Design\MatrixConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\PlaneConverter.cs">
        <Link>Design\PlaneConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\PointConverter.cs">
        <Link>Design\PointConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\QuaternionConverter.cs">
        <Link>Design\QuaternionConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\RayConverter.cs">
        <Link>Design\RayConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\RectangleConverter.cs">
        <Link>Design\RectangleConverter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\Vector2Converter.cs">
        <Link>Design\Vector2Converter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\Vector3Converter.cs">
        <Link>Design\Vector3Converter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Design\Vector4Converter.cs">
        <Link>Design\Vector4Converter.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Alpha8.cs">
        <Link>Graphics\PackedVector\Alpha8.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Bgr565.cs">
        <Link>Graphics\PackedVector\Bgr565.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Bgra4444.cs">
        <Link>Graphics\PackedVector\Bgra4444.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Bgra5551.cs">
        <Link>Graphics\PackedVector\Bgra5551.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Byte4.cs">
        <Link>Graphics\PackedVector\Byte4.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\HalfSingle.cs">
        <Link>Graphics\PackedVector\HalfSingle.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\HalfTypeHelper.cs">
        <Link>Graphics\PackedVector\HalfTypeHelper.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\HalfVector2.cs">
        <Link>Graphics\PackedVector\HalfVector2.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\HalfVector4.cs">
        <Link>Graphics\PackedVector\HalfVector4.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\IPackedVector.cs">
        <Link>Graphics\PackedVector\IPackedVector.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\NormalizedByte2.cs">
        <Link>Graphics\PackedVector\NormalizedByte2.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\NormalizedByte4.cs">
        <Link>Graphics\PackedVector\NormalizedByte4.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\NormalizedShort2.cs">
        <Link>Graphics\PackedVector\NormalizedShort2.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\NormalizedShort4.cs">
        <Link>Graphics\PackedVector\NormalizedShort4.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Rg32.cs">
        <Link>Graphics\PackedVector\Rg32.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Rgba1010102.cs">
        <Link>Graphics\PackedVector\Rgba1010102.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Rgba64.cs">
        <Link>Graphics\PackedVector\Rgba64.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Short2.cs">
        <Link>Graphics\PackedVector\Short2.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Graphics\PackedVector\Short4.cs">
        <Link>Graphics\PackedVector\Short4.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\MathHelper.cs">
        <Link>MathHelper.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Matrix.cs">
        <Link>Matrix.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Plane.cs">
        <Link>Plane.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\PlaneIntersectionType.cs">
        <Link>PlaneIntersectionType.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Point.cs">
        <Link>Point.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Quaternion.cs">
        <Link>Quaternion.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Ray.cs">
        <Link>Ray.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Rectangle.cs">
        <Link>Rectangle.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Vector2.cs">
        <Link>Vector2.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Vector3.cs">
        <Link>Vector3.cs</Link>
      </Compile>
      <Compile Include="..\FNA\src\Vector4.cs">
        <Link>Vector4.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
