using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using WorldXaml.Generator.Common;

namespace NFMWorld.LuaSourceGenerator;

// TODO: operators, constructors, partial TypeTable, lua/ts stubs, pairs, ipairs, # operator, global static initializer on GeneratorGenerated
internal sealed class LuaBindingTypeGenerator(LuaTypeMetadata type) : BaseLuaTypeGenerator
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine();
        sb.AppendLine("namespace NFMWorld.LuaSourceGenerator.Generator");
        using (sb.Block())
        {
            sb.AppendLine("partial class GeneratorGenerated");
            using (sb.Block())
            {
                foreach (var method in type.InstanceMethods)
                {
                    EmitMethod(sb, method);
                }

                foreach (var method in type.StaticMethods)
                {
                    EmitMethod(sb, method);
                }
                
                foreach (var op in type.Operators)
                {
                    EmitMethod(sb, op);
                }

                if (type.HasIndex)
                {
                    EmitIndex(sb, false);
                }

                if (type.HasNewIndex)
                {
                    EmitNewIndex(sb, false);
                }

                if (type.HasStaticIndex)
                {
                    EmitIndex(sb, true);
                }

                if (type.HasStaticNewIndex)
                {
                    EmitNewIndex(sb, true);
                }

                if (!type.IsStatic)
                {
                    EmitToString(sb);

                    EmitMetatable(sb);
                }

                EmitTypeTable(sb);
            }
        }

        if (type.HasLuaVisibleAttr)
        {
            sb.AppendLine($"namespace {type.Namespace}");
            using (sb.Block())
            {
                sb.Append($"{(type.IsStatic ? "static " : "")} {(type.IsRefStruct ? "ref " : "")}{(type.IsRecord ? "partial record " : "partial ")}{(type.IsValueType ? "struct " : !type.IsRecord ? "class " : "")} {type.TypeName}");
                sb.Append(" : global::Lua.ILuaUserData");
                sb.AppendLine();
                using (sb.Block())
                {
                    sb.AppendLine("global::Lua.LuaTable? global::Lua.ILuaUserData.Metatable");
                    using (sb.Block())
                    {
                        sb.AppendLine($"get => global::NFMWorld.LuaSourceGenerator.Generator.GeneratorGenerated.{GetMetatableName(type)};");
                        sb.AppendLine("set => throw new System.InvalidOperationException(\"The metatable of a [LuaVisible] type cannot be assigned to.\")");
                    }

                    if (!type.IsInterface)
                    {
                        sb.AppendLine();

                        sb.AppendLine($"public static implicit operator global::Lua.LuaValue({type.FullTypeName} value)");
                        using (sb.Block())
                        {
                            sb.AppendLine("return global::Lua.LuaValue.FromUserData(value);");
                        }
                    }
                }
            }
        }

        //
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        return sb.ToString();
    }

    private void EmitToString(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.ToString)} = new(\"{Metamethods.ToString}\", (context, ct) =>");
        using (sb.Block(end: "});"))
        {
            sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
            sb.AppendLine("return new System.Threading.Tasks.ValueTask<int>(context.Return(instance.ToString() ?? \"<nil>\"));");
        }
    }

    private void EmitMethod(IndentedStringBuilder sb, LuaMethodMetadata method)
    {
        var argOffset = method.IsStatic ? 0 : 1;
        sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetFunctionName(method)} = new(\"{method.FullLuaName}\", (context, ct) =>");
        using (sb.Block(end: "});"))
        {
            if (!method.IsStatic)
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
            }

            for (var i = 0; i < method.Parameters.Length; i++)
            {
                var p = method.Parameters[i];
                var t = p.Type;
                if (t == null)
                {
                    sb.AppendLine($"#error {p.TypeName} is not INamedTypeSymbol");
                }
                else if (t.IsReferenceType)
                {
                    sb.AppendLine($"var arg{i} = context.GetArgumentOrNullClass<{t.FullTypeName}>({i + argOffset});");
                }
                else if (t.IsNullableValueType)
                {
                    sb.AppendLine($"var arg{i} = context.GetArgumentOrNull<{t.FullTypeName}>({i + argOffset});");
                }
                else
                {
                    sb.AppendLine($"var arg{i} = context.GetArgument<{t.FullTypeName}>({i + argOffset});");
                }
            }

            if (!method.IsVoid)
            {
                sb.Append("var result = ");
            }
            var argExpressions = string.Join(", ", Enumerable.Range(0, method.Parameters.Length).Select(i => $"arg{i}"));
            if (method is LuaOperatorMetadata op)
            {
                if (op.IsUnary)
                {
                    sb.AppendLine($"{op.Operator}arg0;");
                }
                else
                {
                    sb.AppendLine($"arg0 {op.Operator} arg1;");
                }
            }
            else if (method.IsStatic)
            {
                sb.AppendLine($"{method.DeclaringType?.FullTypeName}.{method.Name}({argExpressions});");
            }
            else
            {
                sb.AppendLine($"instance.{method.Name}({argExpressions});");
            }

            if (method.IsVoid)
            {
                sb.AppendLine($"return new global::System.Threading.Tasks.ValueTask<int>(context.Return());");
            }
            else
            {
                sb.AppendLine($"return new global::System.Threading.Tasks.ValueTask<int>(context.Return(");
                using (sb.Indent())
                {
                    if (method.ReturnType != null)
                    {
                        sb.AppendLine(MarshalToLua("result", method.ReturnType));
                    }
                    else
                    {
                        sb.AppendLine($"#error {method.ReturnTypeName} is not INamedTypeSymbol");
                    }
                }
                sb.AppendLine("));");
            }
        }
    }

    // private void EmitCastToLuaValue(IndentedStringBuilder sb)
    // {
    //     if (type.IsInterface) return;
    //     if (type.IsStatic) return;
    //     sb.AppendLine($"public static implicit operator global::Lua.LuaValue({type.FullTypeName} value)");
    //     sb.AppendLine($"    => global::Lua.LuaValue.FromUserData(value, {GetMetatableName(type)});");
    // }

    private void EmitIndex(IndentedStringBuilder sb, bool isStatic)
    {
        sb.AppendLine($"internal static readonly global::Lua.LuaFunction {(isStatic ? GetStaticMetamethodName(type, Metamethods.Index) : GetMetamethodName(type, Metamethods.Index))} = new(\"{Metamethods.Index}\", (context, ct) =>");
        using (sb.Block(end: "});"))
        {
            string instanceExpression;
            if (!isStatic)
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                instanceExpression = "instance";
            }
            else
            {
                instanceExpression = type.FullTypeName;
            }

            sb.AppendLine("var key = context.GetArgument(1);");
            sb.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (sb.Block())
            {
                foreach (var field in isStatic ? type.StaticFields : type.InstanceFields)
                {
                    if (field.FieldType == null)
                    {
                        sb.AppendLine($"#error {field.FieldTypeName} is not INamedTypeSymbol");
                    }
                    else
                    {
                        sb.AppendLine($"if (stringKey == \"{field.LuaName}\") return new global::System.Threading.Tasks.ValueTask<int>(context.Return({MarshalToLua($"{instanceExpression}.{field.Name}", field.FieldType)}));");
                    }
                }
                foreach (var prop in isStatic ? type.StaticProperties : type.InstanceProperties)
                {
                    if (!prop.HasGetter) continue;
                    if (prop.PropertyType == null)
                    {
                        sb.AppendLine($"#error {prop.PropertyTypeName} is not INamedTypeSymbol");
                    }
                    else
                    {
                        sb.AppendLine($"if (stringKey == \"{prop.LuaName}\") return new global::System.Threading.Tasks.ValueTask<int>(context.Return({MarshalToLua($"{instanceExpression}.{prop.Name}", prop.PropertyType)}));");
                    }
                }
            }
            sb.AppendLine("return new System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.Nil));");
        }
    }

    private void EmitNewIndex(IndentedStringBuilder sb, bool isStatic)
    {
        sb.AppendLine($"internal static readonly global::Lua.LuaFunction {(isStatic ? GetStaticMetamethodName(type, Metamethods.NewIndex) : GetMetamethodName(type, Metamethods.NewIndex))} = new(\"{Metamethods.NewIndex}\", (context, ct) =>");
        using (sb.Block(end: "});"))
        {
            string instanceExpression;
            if (!isStatic)
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                instanceExpression = "instance";
            }
            else
            {
                instanceExpression = type.FullTypeName;
            }
            
            sb.AppendLine("var key = context.GetArgument(1);");
            sb.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (sb.Block())
            {
                foreach (var field in isStatic ? type.StaticFields : type.InstanceFields)
                {
                    if (field.IsReadOnly) continue;
                    
                    sb.AppendLine($"if (stringKey == \"{field.LuaName}\")");
                    using (sb.Block())
                    {
                        var t = field.FieldType;
                        if (t.IsReferenceType)
                        {
                            sb.AppendLine($"var value = context.GetArgumentOrNullClass<{t.FullTypeName}>(2);");
                        }
                        else if (t.IsNullableValueType)
                        {
                            sb.AppendLine($"var value = context.GetArgumentOrNull<{t.FullTypeName}>(2);");
                        }
                        else
                        {
                            sb.AppendLine($"var value = context.GetArgument<{t.FullTypeName}>(2);");
                        }

                        sb.AppendLine($"{instanceExpression}.{field.Name} = value;");
                        sb.AppendLine("return new System.Threading.Tasks.ValueTask<int>(context.Return());");
                    }
                }
                foreach (var prop in isStatic ? type.StaticProperties : type.InstanceProperties)
                {
                    if (!prop.HasSetter) continue;
                    
                    sb.AppendLine($"if (stringKey == \"{prop.LuaName}\")");
                    using (sb.Block())
                    {
                        var t = prop.PropertyType;
                        if (t.IsReferenceType)
                        {
                            sb.AppendLine($"var value = context.GetArgumentOrNullClass<{t.FullTypeName}>(2);");
                        }
                        else if (t.IsNullableValueType)
                        {
                            sb.AppendLine($"var value = context.GetArgumentOrNull<{t.FullTypeName}>(2);");
                        }
                        else
                        {
                            sb.AppendLine($"var value = context.GetArgument<{t.FullTypeName}>(2);");
                        }

                        sb.AppendLine($"{instanceExpression}.{prop.Name} = value;");
                        sb.AppendLine("return new System.Threading.Tasks.ValueTask<int>(context.Return());");
                    }
                }

                sb.AppendLine("throw new global::Lua.LuaRuntimeException(context.State, $\"'{stringKey}' not found or read-only.\");");
            }
            sb.AppendLine("throw new global::Lua.LuaRuntimeException(context.State, $\"'{key}' not found.\");");
        }
    }

    private void EmitMetatable(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static global::Lua.LuaTable {GetMetatableName(type)} = null!;");

        sb.AppendLine($"internal static void init_{GetMetatableName(type)}()");
        using (sb.Block())
        {
            sb.AppendLine($"{GetMetatableName(type)} = new global::Lua.LuaTable();");
            if (type.HasIndex)
            {
                sb.AppendLine($"{GetMetatableName(type)}[global::Lua.Runtime.Metamethods.Index] = {GetMetamethodName(type, Metamethods.Index)};");
            }
            if (type.HasNewIndex)
            {
                sb.AppendLine($"{GetMetatableName(type)}[global::Lua.Runtime.Metamethods.NewIndex] = {GetMetamethodName(type, Metamethods.NewIndex)};");
            }
            foreach (var op in type.Operators)
            {
                sb.AppendLine($"{GetMetatableName(type)}[\"{op.MetamethodName}\"] = {GetFunctionName(op)};");
            }
            sb.AppendLine($"{GetMetatableName(type)}[global::Lua.Runtime.Metamethods.ToString] = {GetMetamethodName(type, Metamethods.ToString)};");
            foreach (var method in type.InstanceMethods)
            {
                sb.AppendLine($"{GetMetatableName(type)}[\"{method.LuaName}\"] = {GetFunctionName(method)};");
            }
        }
    }

    private void EmitTypeTable(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static global::Lua.LuaTable {GetTypeTableName(type)} = null!;");

        sb.AppendLine($"internal static void init_{GetTypeTableName(type)}()");
        using (sb.Block())
        {
            sb.AppendLine($"{GetTypeTableName(type)} = new global::Lua.LuaTable();");
            if (type.HasStaticIndex)
            {
                sb.AppendLine($"{GetTypeTableName(type)}[global::Lua.Runtime.Metamethods.Index] = {GetStaticMetamethodName(type, Metamethods.Index)};");
            }
            if (type.HasStaticNewIndex)
            {
                sb.AppendLine($"{GetTypeTableName(type)}[global::Lua.Runtime.Metamethods.NewIndex] = {GetStaticMetamethodName(type, Metamethods.NewIndex)};");
            }
            foreach (var method in type.StaticMethods)
            {
                sb.AppendLine($"{GetTypeTableName(type)}[\"{method.LuaName}\"] = {GetFunctionName(method)};");
            }
        }
    }
}

internal static class Metamethods
{
    public const string Metatable = "__metatable";
    public const string Index = "__index";
    public const string NewIndex = "__newindex";
    public const string Add = "__add";
    public const string Sub = "__sub";
    public const string Mul = "__mul";
    public const string Div = "__div";
    public const string Mod = "__mod";
    public const string Pow = "__pow";
    public const string Unm = "__unm";
    public const string Len = "__len";
    public const string Eq = "__eq";
    public const string Lt = "__lt";
    public const string Le = "__le";
    public const string Call = "__call";
    public const string Concat = "__concat";
    public const string Pairs = "__pairs";
    public const string IPairs = "__ipairs";
    public new const string ToString = "__tostring";
}

internal abstract class BaseLuaTypeGenerator
{
    protected static string MarshalToLua(string variable, BaseLuaTypeMetadata variableType)
    {
        if (variableType.IsBuiltIn)
        {
            return variable;
        }

        if (variableType.IsILuaUserData || variableType.HasLuaVisibleAttr)
        {
            return $"global::Lua.LuaValue.FromUserData({variable})";
        }
        
        return $"global::Lua.LuaValue.FromUserData({variable}, {GetMetatableName(variableType)})";
    }
    
    [return: NotNullIfNotNull(nameof(ns))]
    protected static string? ToIdentifier(string? ns) =>
        ns?.Replace(".", "_");
    protected static string GetFunctionName(LuaMethodMetadata method) => $"__function_{ToIdentifier(method.DeclaringType?.LuaName)}_{method.FullLuaName}";
    protected static string GetMetamethodName(BaseLuaTypeMetadata type, string metamethod) => $"__metamethod_{ToIdentifier(type.LuaName)}_{metamethod}";
    protected static string GetStaticMetamethodName(BaseLuaTypeMetadata type, string metamethod) => $"__metamethod__static_{ToIdentifier(type.LuaName)}_{metamethod}";
    protected static string GetMetatableName(BaseLuaTypeMetadata type) => $"__metatable_{ToIdentifier(type.LuaName)}";
    protected static string GetTypeTableName(BaseLuaTypeMetadata type) => $"__typeTable_{ToIdentifier(type.LuaName)}";
}
