using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using WorldXaml.Generator.Common;

namespace NFMWorld.LuaSourceGenerator;

// TODO: indexer, lua/ts stubs, global static initializer on GeneratorGenerated
internal sealed class LuaBindingTypeGenerator(LuaTypeMetadata type) : BaseLuaTypeGenerator
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine();
        sb.AppendLine("namespace NFMWorld.LuaSourceGenerator.Generator");
        using (sb.Block())
        {
            sb.AppendLine("partial class GeneratorGenerated");
            using (sb.Block())
            {
                foreach (var method in type.InstanceMethods)
                {
                    EmitMethod(sb, method);
                }

                foreach (var method in type.StaticMethods)
                {
                    EmitMethod(sb, method);
                }
                
                foreach (var op in type.Operators)
                {
                    EmitMethod(sb, op);
                }
                
                foreach (var ctor in type.Constructors)
                {
                    EmitMethod(sb, ctor);
                }

                if (type.HasIndex)
                {
                    EmitIndex(sb, false);
                }

                if (type.HasNewIndex)
                {
                    EmitNewIndex(sb, false);
                }

                if (type.HasStaticIndex)
                {
                    EmitIndex(sb, true);
                }

                if (type.HasStaticNewIndex)
                {
                    EmitNewIndex(sb, true);
                }

                if (!type.IsStatic)
                {
                    EmitToString(sb);

                    EmitMetatable(sb);
                }

                if (type.HasPairsAndIPairs)
                {
                    EmitPairsAndIPairs(sb);
                }

                if (type.HasLengthOrCount)
                {
                    EmitLen(sb);
                }

                EmitTypeTable(sb);
            }
        }

        if (type.HasLuaVisibleAttr)
        {
            sb.AppendLine($"namespace {type.Namespace}");
            using (sb.Block())
            {
                sb.Append($"{(type.IsStatic ? "static " : "")} partial {(type.IsRefStruct ? "ref " : "")}{(type.IsRecord ? "record " : "")}{(type.IsValueType ? "struct " : "class ")} {type.TypeName}");
                sb.Append(" : global::Lua.ILuaUserData");
                sb.AppendLine();
                using (sb.Block())
                {
                    sb.AppendLine("global::Lua.LuaTable? global::Lua.ILuaUserData.Metatable");
                    using (sb.Block())
                    {
                        sb.AppendLine($"get => global::NFMWorld.LuaSourceGenerator.Generator.GeneratorGenerated.{GetMetatableName(type)};");
                        sb.AppendLine("set => throw new System.InvalidOperationException(\"The metatable of a [LuaVisible] type cannot be assigned to.\")");
                    }

                    sb.AppendLine($"public static global::Lua.LuaTable TypeTable => global::NFMWorld.LuaSourceGenerator.Generator.GeneratorGenerated.{GetTypeTableName(type)};");

                    if (!type.IsInterface && !type.IsStatic)
                    {
                        sb.AppendLine();

                        sb.AppendLine($"public static implicit operator global::Lua.LuaValue({type.FullTypeName} value)");
                        using (sb.Block())
                        {
                            sb.AppendLine("return global::Lua.LuaValue.FromUserData(value);");
                        }
                    }
                }
            }
        }

        //
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        return sb.ToString();
    }

    private void EmitLen(IndentedStringBuilder sb)
    {
        if (type.HasLength)
        {
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.Len)} = new(\"{Metamethods.Len}\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(instance.Length));");
            }
        }
        else if (type.HasCount)
        {
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.Len)} = new(\"{Metamethods.Len}\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(instance.Count));");
            }
        }
        else if (type.IsInlineArray)
        {
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.Len)} = new(\"{Metamethods.Len}\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                sb.AppendLine($"return global::System.Threading.Tasks.ValueTask.FromResult(context.Return({type.InlineArrayLength}));");
            }
        }
        else if (type.IsIEnumerable && type.IEnumerableType is {} enumerableType)
        {
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.Len)} = new(\"{Metamethods.Len}\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                sb.AppendLine($"return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(global::System.Linq.Enumerable.Count<{enumerableType.FullTypeName}>(instance)));");
            }
        }
    }

    private void EmitPairsAndIPairs(IndentedStringBuilder sb)
    {
        // for array, inlinearray, and ienumerable, implement pairs and ipairs with the same function
        // for ienumerable of keyvaluepair, implement pairs with key-value logic and ipairs with index logic
        if (type.IsArray)
        {
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction __next_{ToIdentifier(type.LuaName)} = new(\"next\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                sb.AppendLine("var index = context.GetArgument<int>(1); // 1-based");
                sb.AppendLine("index += 1;");
                sb.AppendLine("if (index >= instance.Length)");
                using (sb.Block())
                {
                    sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return());");
                }

                sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(instance[index - 1]));");
            }
            
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.Pairs)} = new(\"{Metamethods.Pairs}\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine("var table = context.GetArgument(0);");
                sb.AppendLine("var index = 0;");
                
                sb.AppendLine($"return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(__next_{ToIdentifier(type.LuaName)}, table, index));");
            }
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.IPairs)} = {GetMetamethodName(type, Metamethods.Pairs)};");
        }
        else if (type.IsInlineArray)
        {
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction __next_{ToIdentifier(type.LuaName)} = new(\"next\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                sb.AppendLine("var index = context.GetArgument<int>(1); // 1-based");
                sb.AppendLine("index += 1;");
                sb.AppendLine($"if (index >= {type.InlineArrayLength!})");
                using (sb.Block())
                {
                    sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return());");
                }

                sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(instance[index - 1]));");
            }
            
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.Pairs)} = new(\"{Metamethods.Pairs}\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine("var table = context.GetArgument(0);");
                sb.AppendLine("var index = 0;");
                
                sb.AppendLine($"return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(__next_{ToIdentifier(type.LuaName)}, table, index));");
            }
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.IPairs)} = {GetMetamethodName(type, Metamethods.Pairs)};");
        }
        else if (type.IsIEnumerableOfKeyValuePair && type.IEnumerableType is { } kvpType && type.IEnumerableKeyType is { } kvpKeyType && type.IEnumerableValueType is { } kvpValueType)
        {
            // ipairs
            sb.AppendLine($"internal static readonly Func<global::Lua.LuaFunctionExecutionContext, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<int>> __inext_{ToIdentifier(type.LuaName)} = static (context, ct) =>");
            using (sb.Block(end: "};"))
            {
                sb.AppendLine($"var instance = context.GetCsClosure()!.UpValues[0].Read<global::System.Collections.IEnumerator<{kvpType.FullTypeName}>>();");
                sb.AppendLine("var idx = context.GetCsClosure()!.UpValues[1].Read<int>();");
                sb.AppendLine("context.GetCsClosure()!.UpValues[1] = idx + 1;");
                sb.AppendLine("if (!instance.MoveNext())");
                using (sb.Block())
                {
                    sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return());");
                }
                
                sb.AppendLine($"return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(idx + 1, {MarshalToLua("instance.Current", kvpType)});");
            }

            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.IPairs)} = new(\"{Metamethods.IPairs}\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine($"var instance = context.GetArgument<global::System.Collections.Generic.IEnumerable<{kvpType.FullTypeName}>>(0);");
                
                // upvalues: instance, idx
                sb.AppendLine($"var closure = new global::Lua.Runtime.CSharpClosure(\"inext\", [LuaValue.FromLightUserData(instance), 0], __inext_{ToIdentifier(type.LuaName)});");
                
                sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(closure, LuaValue.Nil, LuaValue.Nil));");
            }
            
            // pairs
            sb.AppendLine($"internal static readonly Func<global::Lua.LuaFunctionExecutionContext, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<int>> __next_{ToIdentifier(type.LuaName)} = static (context, ct) =>");
            using (sb.Block(end: "};"))
            {
                sb.AppendLine($"var instance = context.GetCsClosure()!.UpValues[0].Read<global::System.Collections.IEnumerator<{kvpType.FullTypeName}>>();");
                sb.AppendLine("if (!instance.MoveNext())");
                using (sb.Block())
                {
                    sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return());");
                }
                
                sb.AppendLine($"return global::System.Threading.Tasks.ValueTask.FromResult(context.Return({MarshalToLua("instance.Current.Key", kvpKeyType)}, {MarshalToLua("instance.Current.Value", kvpValueType)});");
            }

            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.Pairs)} = new(\"{Metamethods.Pairs}\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine($"var instance = context.GetArgument<global::System.Collections.Generic.IEnumerable<{kvpType.FullTypeName}>>(0);");
                
                // upvalues: instance, idx
                sb.AppendLine($"var closure = new global::Lua.Runtime.CSharpClosure(\"next\", [LuaValue.FromLightUserData(instance)], __next_{ToIdentifier(type.LuaName)});");
                
                sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(closure, LuaValue.Nil, LuaValue.Nil));");
            }
        }
        else if (type.IsIEnumerable && type.IEnumerableType is { } elementType)
        {
            sb.AppendLine($"internal static readonly Func<global::Lua.LuaFunctionExecutionContext, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<int>> __next_{ToIdentifier(type.LuaName)} = static (context, ct) =>");
            using (sb.Block(end: "};"))
            {
                sb.AppendLine($"var instance = context.GetCsClosure()!.UpValues[0].Read<global::System.Collections.IEnumerator<{elementType.FullTypeName}>>();");
                sb.AppendLine("var idx = context.GetCsClosure()!.UpValues[1].Read<int>();");
                sb.AppendLine("context.GetCsClosure()!.UpValues[1] = idx + 1;");
                sb.AppendLine("if (!instance.MoveNext())");
                using (sb.Block())
                {
                    sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return());");
                }
                
                sb.AppendLine($"return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(idx + 1, {MarshalToLua("instance.Current", elementType)});");
            }

            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.Pairs)} = new(\"{Metamethods.Pairs}\", (context, ct) =>");
            using (sb.Block(end: "});"))
            {
                sb.AppendLine($"var instance = context.GetArgument<global::System.Collections.Generic.IEnumerable<{elementType.FullTypeName}>>(0);");
                
                // upvalues: instance, idx
                sb.AppendLine($"var closure = new global::Lua.Runtime.CSharpClosure(\"next\", [LuaValue.FromLightUserData(instance), 0], __next_{ToIdentifier(type.LuaName)});");
                
                sb.AppendLine("return global::System.Threading.Tasks.ValueTask.FromResult(context.Return(closure, LuaValue.Nil, LuaValue.Nil));");
            }
            sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.IPairs)} = {GetMetamethodName(type, Metamethods.Pairs)};");
        }
    }

    private void EmitToString(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.ToString)} = new(\"{Metamethods.ToString}\", (context, ct) =>");
        using (sb.Block(end: "});"))
        {
            sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
            sb.AppendLine("return new System.Threading.Tasks.ValueTask<int>(context.Return(instance.ToString() ?? \"<nil>\"));");
        }
    }

    private void EmitMethod(IndentedStringBuilder sb, LuaMethodMetadata method)
    {
        var argOffset = method.IsStatic ? 0 : 1;
        sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetFunctionName(method)} = new(\"{method.FullLuaName}\", (context, ct) =>");
        using (sb.Block(end: "});"))
        {
            if (!method.IsStatic && !method.IsInstanceConstructor)
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
            }

            for (var i = 0; i < method.Parameters.Length; i++)
            {
                var p = method.Parameters[i];
                var t = p.Type;
                if (t == null)
                {
                    sb.AppendLine($"#error {p.TypeName} is not INamedTypeSymbol");
                }
                else if (t.IsReferenceType)
                {
                    sb.AppendLine($"var arg{i} = context.GetArgumentOrNullClass<{t.FullTypeName}>({i + argOffset});");
                }
                else if (t.IsNullableValueType)
                {
                    sb.AppendLine($"var arg{i} = context.GetArgumentOrNull<{t.FullTypeName}>({i + argOffset});");
                }
                else
                {
                    sb.AppendLine($"var arg{i} = context.GetArgument<{t.FullTypeName}>({i + argOffset});");
                }
            }

            if (!method.IsVoid)
            {
                sb.Append("var result = ");
            }
            var argExpressions = string.Join(", ", Enumerable.Range(0, method.Parameters.Length).Select(i => $"arg{i}"));
            if (method is LuaConstructorMetadata ctor)
            {
                sb.AppendLine($"new {method.DeclaringType?.FullTypeName}({argExpressions});");
            }
            else if (method is LuaOperatorMetadata op)
            {
                if (op.IsUnary)
                {
                    sb.AppendLine($"{op.Operator}arg0;");
                }
                else
                {
                    sb.AppendLine($"arg0 {op.Operator} arg1;");
                }
            }
            else if (method.IsStatic)
            {
                sb.AppendLine($"{method.DeclaringType?.FullTypeName}.{method.Name}({argExpressions});");
            }
            else
            {
                sb.AppendLine($"instance.{method.Name}({argExpressions});");
            }

            if (method.IsVoid)
            {
                sb.AppendLine($"return new global::System.Threading.Tasks.ValueTask<int>(context.Return());");
            }
            else
            {
                sb.AppendLine($"return new global::System.Threading.Tasks.ValueTask<int>(context.Return(");
                using (sb.Indent())
                {
                    if (method.ReturnType != null)
                    {
                        sb.AppendLine(MarshalToLua("result", method.ReturnType));
                    }
                    else
                    {
                        sb.AppendLine($"#error {method.ReturnTypeName} is not INamedTypeSymbol");
                    }
                }
                sb.AppendLine("));");
            }
        }
    }

    private void EmitIndex(IndentedStringBuilder sb, bool isStatic)
    {
        sb.AppendLine($"internal static readonly global::Lua.LuaFunction {(isStatic ? GetStaticMetamethodName(type, Metamethods.Index) : GetMetamethodName(type, Metamethods.Index))} = new(\"{Metamethods.Index}\", (context, ct) =>");
        using (sb.Block(end: "});"))
        {
            string instanceExpression;
            if (!isStatic)
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                instanceExpression = "instance";
            }
            else
            {
                instanceExpression = type.FullTypeName;
            }

            sb.AppendLine("var key = context.GetArgument(1);");
            sb.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (sb.Block())
            {
                // TODO replace with switch statement for runtime perf
                foreach (var field in isStatic ? type.StaticFields : type.InstanceFields)
                {
                    if (field.FieldType == null)
                    {
                        sb.AppendLine($"#error {field.FieldTypeName} is not INamedTypeSymbol");
                    }
                    else
                    {
                        sb.AppendLine($"if (stringKey == \"{field.LuaName}\") return new global::System.Threading.Tasks.ValueTask<int>(context.Return({MarshalToLua($"{instanceExpression}.{field.Name}", field.FieldType)}));");
                    }
                }
                foreach (var prop in isStatic ? type.StaticProperties : type.InstanceProperties)
                {
                    if (!prop.HasGetter) continue;
                    if (prop.PropertyType == null)
                    {
                        sb.AppendLine($"#error {prop.PropertyTypeName} is not INamedTypeSymbol");
                    }
                    else
                    {
                        sb.AppendLine($"if (stringKey == \"{prop.LuaName}\") return new global::System.Threading.Tasks.ValueTask<int>(context.Return({MarshalToLua($"{instanceExpression}.{prop.Name}", prop.PropertyType)}));");
                    }
                }

                // static method dispatch goes via the type table, userdata cannot have key/values so instance method
                // dispatch goes via __index
                if (!isStatic)
                {
                    foreach (var method in type.InstanceMethods)
                    {
                        sb.AppendLine($"if (stringKey == \"{method.LuaName}\") return new global::System.Threading.Tasks.ValueTask<int>(context.Return({GetFunctionName(method)}));");
                    }
                }
            }
            sb.AppendLine("return new System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.Nil));");
        }
    }

    private void EmitNewIndex(IndentedStringBuilder sb, bool isStatic)
    {
        sb.AppendLine($"internal static readonly global::Lua.LuaFunction {(isStatic ? GetStaticMetamethodName(type, Metamethods.NewIndex) : GetMetamethodName(type, Metamethods.NewIndex))} = new(\"{Metamethods.NewIndex}\", (context, ct) =>");
        using (sb.Block(end: "});"))
        {
            string instanceExpression;
            if (!isStatic)
            {
                sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
                instanceExpression = "instance";
            }
            else
            {
                instanceExpression = type.FullTypeName;
            }
            
            sb.AppendLine("var key = context.GetArgument(1);");
            sb.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (sb.Block())
            {
                // TODO replace with switch statement for runtime perf
                foreach (var field in isStatic ? type.StaticFields : type.InstanceFields)
                {
                    if (field.IsReadOnly) continue;
                    
                    sb.AppendLine($"if (stringKey == \"{field.LuaName}\")");
                    using (sb.Block())
                    {
                        var t = field.FieldType;
                        if (t.IsReferenceType)
                        {
                            sb.AppendLine($"var value = context.GetArgumentOrNullClass<{t.FullTypeName}>(2);");
                        }
                        else if (t.IsNullableValueType)
                        {
                            sb.AppendLine($"var value = context.GetArgumentOrNull<{t.FullTypeName}>(2);");
                        }
                        else
                        {
                            sb.AppendLine($"var value = context.GetArgument<{t.FullTypeName}>(2);");
                        }

                        sb.AppendLine($"{instanceExpression}.{field.Name} = value;");
                        sb.AppendLine("return new System.Threading.Tasks.ValueTask<int>(context.Return());");
                    }
                }
                foreach (var prop in isStatic ? type.StaticProperties : type.InstanceProperties)
                {
                    if (!prop.HasSetter) continue;
                    
                    sb.AppendLine($"if (stringKey == \"{prop.LuaName}\")");
                    using (sb.Block())
                    {
                        var t = prop.PropertyType;
                        if (t.IsReferenceType)
                        {
                            sb.AppendLine($"var value = context.GetArgumentOrNullClass<{t.FullTypeName}>(2);");
                        }
                        else if (t.IsNullableValueType)
                        {
                            sb.AppendLine($"var value = context.GetArgumentOrNull<{t.FullTypeName}>(2);");
                        }
                        else
                        {
                            sb.AppendLine($"var value = context.GetArgument<{t.FullTypeName}>(2);");
                        }

                        sb.AppendLine($"{instanceExpression}.{prop.Name} = value;");
                        sb.AppendLine("return new System.Threading.Tasks.ValueTask<int>(context.Return());");
                    }
                }

                sb.AppendLine("throw new global::Lua.LuaRuntimeException(context.State, $\"'{stringKey}' not found or read-only.\");");
            }
            sb.AppendLine("throw new global::Lua.LuaRuntimeException(context.State, $\"'{key}' not found.\");");
        }
    }

    private void EmitMetatable(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static global::Lua.LuaTable {GetMetatableName(type)} = null!;");

        sb.AppendLine($"internal static void init_{GetMetatableName(type)}()");
        using (sb.Block())
        {
            sb.AppendLine($"{GetMetatableName(type)} = new global::Lua.LuaTable();");
            if (type.HasIndex)
            {
                sb.AppendLine($"{GetMetatableName(type)}[global::Lua.Runtime.Metamethods.Index] = {GetMetamethodName(type, Metamethods.Index)};");
            }
            if (type.HasNewIndex)
            {
                sb.AppendLine($"{GetMetatableName(type)}[global::Lua.Runtime.Metamethods.NewIndex] = {GetMetamethodName(type, Metamethods.NewIndex)};");
            }
            if (type.HasPairsAndIPairs)
            {
                sb.AppendLine($"{GetMetatableName(type)}[global::Lua.Runtime.Metamethods.Pairs] = {GetMetamethodName(type, Metamethods.Pairs)};");
                sb.AppendLine($"{GetMetatableName(type)}[global::Lua.Runtime.Metamethods.IPairs] = {GetMetamethodName(type, Metamethods.IPairs)};");
            }
            foreach (var op in type.Operators)
            {
                sb.AppendLine($"{GetMetatableName(type)}[\"{op.MetamethodName}\"] = {GetFunctionName(op)};");
            }
            sb.AppendLine($"{GetMetatableName(type)}[global::Lua.Runtime.Metamethods.ToString] = {GetMetamethodName(type, Metamethods.ToString)};");
        }
    }

    private void EmitTypeTable(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static global::Lua.LuaTable {GetTypeTableName(type)} = null!;");

        sb.AppendLine($"internal static void init_{GetTypeTableName(type)}()");
        using (sb.Block())
        {
            sb.AppendLine($"{GetTypeTableName(type)} = new global::Lua.LuaTable();");
            
            // static mt
            sb.AppendLine($"var {GetTypeTableName(type)}_metatable = new global::Lua.LuaTable();");
            if (type.HasStaticIndex)
            {
                sb.AppendLine($"{GetTypeTableName(type)}_metatable[global::Lua.Runtime.Metamethods.Index] = {GetStaticMetamethodName(type, Metamethods.Index)};");
            }
            if (type.HasStaticNewIndex)
            {
                sb.AppendLine($"{GetTypeTableName(type)}_metatable[global::Lua.Runtime.Metamethods.NewIndex] = {GetStaticMetamethodName(type, Metamethods.NewIndex)};");
            }
            sb.AppendLine($"{GetTypeTableName(type)}.Metatable = {GetTypeTableName(type)}_metatable;");
            
            // static type table
            foreach (var method in type.StaticMethods)
            {
                sb.AppendLine($"{GetTypeTableName(type)}[\"{method.FullLuaName}\"] = {GetFunctionName(method)};");
            }
            foreach (var ctor in type.Constructors)
            {
                sb.AppendLine($"{GetTypeTableName(type)}[\"{ctor.FullLuaName}\"] = {GetFunctionName(ctor)};");
            }
            
            // lua convention: static type table gets instance methods taking self as first parameter
            // it's very rare that you'd use these, but tooling expects it to be there
            foreach (var method in type.InstanceMethods)
            {
                sb.AppendLine($"{GetTypeTableName(type)}[\"{method.FullLuaName}\"] = {GetFunctionName(method)};");
            }
        }
    }
}

internal static class Metamethods
{
    public const string Metatable = "__metatable";
    public const string Index = "__index";
    public const string NewIndex = "__newindex";
    public const string Add = "__add";
    public const string Sub = "__sub";
    public const string Mul = "__mul";
    public const string Div = "__div";
    public const string Mod = "__mod";
    public const string Pow = "__pow";
    public const string Unm = "__unm";
    public const string Len = "__len";
    public const string Eq = "__eq";
    public const string Lt = "__lt";
    public const string Le = "__le";
    public const string Call = "__call";
    public const string Concat = "__concat";
    public const string Pairs = "__pairs";
    public const string IPairs = "__ipairs";
    public new const string ToString = "__tostring";
}

internal abstract class BaseLuaTypeGenerator
{
    protected static string MarshalToLua(string variable, BaseLuaTypeMetadata variableType)
    {
        if (variableType.IsBuiltIn)
        {
            return variable;
        }

        if (variableType.IsILuaUserData || variableType.HasLuaVisibleAttr)
        {
            return $"global::Lua.LuaValue.FromUserData({variable})";
        }
        
        return $"global::Lua.LuaValue.FromUserData({variable}, {GetMetatableName(variableType)})";
    }
    
    [return: NotNullIfNotNull(nameof(ns))]
    protected static string? ToIdentifier(string? ns) =>
        ns?.Replace(".", "_");
    protected static string GetFunctionName(LuaMethodMetadata method) => $"__function_{ToIdentifier(method.DeclaringType?.LuaName)}_{method.FullLuaName}";
    protected static string GetMetamethodName(BaseLuaTypeMetadata type, string metamethod) => $"__metamethod_{ToIdentifier(type.LuaName)}_{metamethod}";
    protected static string GetStaticMetamethodName(BaseLuaTypeMetadata type, string metamethod) => $"__metamethod__static_{ToIdentifier(type.LuaName)}_{metamethod}";
    protected static string GetMetatableName(BaseLuaTypeMetadata type) => $"__metatable_{ToIdentifier(type.LuaName)}";
    protected static string GetTypeTableName(BaseLuaTypeMetadata type) => $"__typeTable_{ToIdentifier(type.LuaName)}";
}
