using WorldXaml.Generator.Common;

namespace NFMWorld.LuaSourceGenerator;

internal sealed class LuaBindingEnumTypeGenerator(LuaTypeMetadata type) : BaseLuaTypeGenerator
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine();
        sb.AppendLine("namespace NFMWorld.LuaSourceGenerator.Generator;");
        sb.AppendLine("partial class GeneratorGenerated");
        using (sb.Block())
        {
            sb.AppendLine(
                $$"""
                internal static global::Lua.LuaTable {{GetMetatableName(type)}} = null;
                internal static global::Lua.LuaTable {{GetTypeTableName(type)}} = null;

                internal static void init_{{GetMetatableName(type)}}()
                {
                    {{GetMetatableName(type)}} = new global::Lua.LuaTable(0, 1);
                    {{GetMetatableName(type)}}[global::Lua.Runtime.Metamethods.ToString] = new global::Lua.LuaFunction("{{Metamethods.ToString}}", (context, ct) =>
                    {
                        var instance = context.GetArgument<{{type.FullTypeName}}>(0);
                        return new(context.Return(global::System.Enum.GetName(typeof({{type.FullTypeName}}), instance) ?? instance.ToString()));
                    });
                }
                """);

            sb.AppendLine($"internal static void init_{GetTypeTableName(type)}()");
            using (sb.Block())
            {
                sb.AppendLine($"{GetTypeTableName(type)} = new global::Lua.LuaTable(0, {type.EnumMembers.Length});");
                foreach (var member in type.EnumMembers)
                {
                    sb.AppendLine($"{GetTypeTableName(type)}[\"{member.LuaName}\"] = {MarshalToLua($"{type.FullTypeName}.{member.Name}", member.FieldType)};");
                }
            }
        }
        //
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        return sb.ToString();
    }
}