using WorldXaml.Generator.Common;

namespace NFMWorld.LuaSourceGenerator;

internal sealed class LuaBindingStubTypeGenerator(BaseLuaTypeMetadata type) : BaseLuaTypeGenerator
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine();
        sb.AppendLine("namespace NFMWorld.LuaSourceGenerator.Generator;");
        sb.AppendLine("partial class GeneratorGenerated");
        using (sb.Block())
        {
            EmitToString(sb);
            EmitMetatable(sb);
        }
        //
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        return sb.ToString();
    }

    private void EmitToString(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static readonly global::Lua.LuaFunction {GetMetamethodName(type, Metamethods.ToString)} = new(\"{Metamethods.ToString}\", (context, ct) =>");
        using (sb.Block(end: "});"))
        {
            sb.AppendLine($"var instance = context.GetArgument<{type.FullTypeName}>(0);");
            sb.AppendLine("return new System.Threading.Tasks.ValueTask<int>(context.Return(instance.ToString() ?? \"<nil>\"));");
        }
    }

    private void EmitMetatable(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static global::Lua.LuaTable {GetMetatableName(type)} = null!;");

        sb.AppendLine($"internal static void init_{GetMetatableName(type)}()");
        using (sb.Block())
        {
            sb.AppendLine($"{GetMetatableName(type)} = new global::Lua.LuaTable();");
            sb.AppendLine($"{GetMetatableName(type)}[global::Lua.Runtime.Metamethods.ToString] = {GetMetamethodName(type, Metamethods.ToString)};");
        }
    }
}