using WorldXaml.Generator.Common;

namespace NFMWorld.LuaSourceGenerator;

internal sealed class LuaBindingInitGenerator(
    IReadOnlyList<BaseLuaTypeMetadata> types,
    IReadOnlyList<BaseLuaTypeMetadata> stubTypes
) : BaseLuaTypeGenerator
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine();
        sb.AppendLine("namespace NFMWorld.LuaSourceGenerator.Generator");
        using (sb.Block())
        {
            sb.AppendLine("partial class GeneratorGenerated");
            using (sb.Block())
            {
                sb.AppendLine("static GeneratorGenerated()");
                using (sb.Block())
                {
                    foreach (var type in types)
                    {
                        if (!type.IsStatic)
                        {
                            sb.AppendLine($"init_{GetMetatableName(type)}();");
                            sb.AppendLine($"global::NFMWorld.LuaSourceGenerator.Generator.LuaVisibleTypeMetatableRegistry<{type.FullTypeName}>.Register({GetMetatableName(type)});");
                        }

                        sb.AppendLine($"init_{GetTypeTableName(type)}();");
                    }
                }
            }

            sb.AppendLine("public static class LuaVisibleTypeRegistry");
            using (sb.Block())
            {
                EmitRegisterAll(sb);
            }
            
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Thread-safe registry mapping each <typeparamref name=\"T\"/> to its code-generated StructUserData metatable.");
            sb.AppendLine("/// Populated at assembly load time by the source-generated <see cref=\"StructUserDataMetatableInitializer\"/>.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public static class LuaVisibleTypeMetatableRegistry<T>");
            using (sb.Block())
            {
                sb.AppendLine("public static global::Lua.LuaTable? Metatable { get; private set; }");
                sb.AppendLine("internal static void Register(global::Lua.LuaTable metatable) => Metatable = metatable;");
            }
        }

        //
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        return sb.ToString();
    }
    
    private void EmitRegisterAll(IndentedStringBuilder sb)
    {
        sb.AppendLine("public static void RegisterAll(global::Lua.LuaState state)");
        using (sb.Block())
        {
            foreach (var type in types)
            {
                sb.AppendLine($"state.Environment[\"{type.LuaName}\"] = global::NFMWorld.LuaSourceGenerator.Generator.GeneratorGenerated.{GetTypeTableName(type)};");
            }
        }
    }
}