namespace NFMWorld.LuaSourceGenerator;

internal sealed class LuaBindingTypeGenerator
{
    private readonly LuaTypeMetadata _type;
    private readonly int _i;
    private readonly HashSet<string> _knownLuaVisibleFullNames;

    public LuaBindingTypeGenerator(LuaTypeMetadata type, HashSet<string> knownLuaVisibleFullNames, int baseIndent = 0)
    {
        _type = type;
        _i = baseIndent;
        _knownLuaVisibleFullNames = knownLuaVisibleFullNames;
    }

    public string GenerateCode()
    {
        var sb = new CodeBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine();
        var ns = _type.Namespace;
        if (!string.IsNullOrEmpty(ns)) sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        var kw = _type.IsInterface ? "interface" : _type.IsValueType ? (_type.IsRecord ? "record struct" : "struct") : (_type.IsRecord ? "record" : "class");
        var iface = _type.IsStatic ? "" : " : global::Lua.ILuaUserData";
        // "static partial class" (correct order), not "partial static class"
        var staticMod = _type.IsStatic ? "static " : "";
        var partialMod = "partial ";
        W(sb, _i, $"{staticMod}{partialMod}{kw} {_type.TypeName}{iface}");
        W(sb, _i, "{");
        var inner = _i + 1;
        Cache(sb, inner);
        if (!_type.IsStatic) Metatable(sb, inner);
        TypeTable(sb, inner);
        if (!_type.IsStatic) { Explicit(sb, inner); Operator(sb, inner); }
        W(sb, _i, "}");
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        return sb.ToString();
    }

    private void Cache(CodeBuilder sb, int i)
    {
        W(sb, i, "private static class __Cache");
        W(sb, i, "{");
        var b = i + 1;
        if (!_type.IsStatic) { Methods(sb, b); Events(sb, b); Index(sb, b); NewIndex(sb, b); Tostring(sb, b); }
        // Static members and constructors
        StaticMethods(sb, b);
        Constructors(sb, b);
        W(sb, b, "internal static global::Lua.LuaTable? __metatable;");
        W(sb, b, "internal static global::Lua.LuaTable? __typeTable;");
        W(sb, i, "}");
        sb.AppendLine();
    }

    // ---------------------------------------------------------------
    // Constructors
    // ---------------------------------------------------------------
    private void Constructors(CodeBuilder sb, int i)
    {
        foreach (var ctor in _type.Constructors)
        {
            var paramList = ctor.Parameters;
            var argNames = string.Join(", ", Enumerable.Range(0, paramList.Length).Select(pi =>
                paramList[pi].NeedsStructUserData ? $"arg{pi}.Value" : $"arg{pi}"));

            W(sb, i, $"internal static readonly global::Lua.LuaFunction __function_new{ctor.OverloadSuffix} = new(\"new\", (context, ct) =>");
            W(sb, i, "{");
            var b = i + 1;
            for (var pi = 0; pi < paramList.Length; pi++)
                W(sb, b, $"var arg{pi} = context.GetArgument<{Ts(paramList[pi])}>({pi});");
            W(sb, b, $"var __result = new {_type.FullTypeName}({argNames});");
            W(sb, b, "return new System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.FromUserData(__result)));");
            W(sb, i, "}");
            W(sb, i, ");");
            sb.AppendLine();
        }
    }

    // ---------------------------------------------------------------
    // Static methods
    // ---------------------------------------------------------------
    private void StaticMethods(CodeBuilder sb, int i)
    {
        foreach (var m in _type.StaticMethods)
        {
            var ret = m.ReturnType == "void";
            var paramList = m.Parameters;
            W(sb, i, $"internal static readonly global::Lua.LuaFunction __function_static_{m.FullLuaName} = new(\"{m.LuaName}\", (context, ct) =>");
            W(sb, i, "{");
            var b = i + 1;
            for (var pi = 0; pi < paramList.Length; pi++)
                W(sb, b, $"var arg{pi} = context.GetArgument<{Ts(paramList[pi])}>({pi});");
            var args = string.Join(", ", Enumerable.Range(0, paramList.Length).Select(pi =>
                paramList[pi].NeedsStructUserData ? $"arg{pi}.Value" : $"arg{pi}"));

            if (ret) { W(sb, b, $"{_type.FullTypeName}.{m.Name}({args});"); W(sb, b, "return new System.Threading.Tasks.ValueTask<int>(context.Return());"); }
            else { W(sb, b, $"var __result = {_type.FullTypeName}.{m.Name}({args});"); W(sb, b, $"return new System.Threading.Tasks.ValueTask<int>(context.Return({WrRet("__result", m)}));"); }
            W(sb, i, "}");
            W(sb, i, ");");
            sb.AppendLine();
        }
    }
    private void Methods(CodeBuilder sb, int i)
    {
        foreach (var m in _type.InstanceMethods)
        {
            if (m.IsInherited) continue;

            var ret = m.ReturnType == "void";
            W(sb, i, $"internal static readonly global::Lua.LuaFunction __function_{m.FullLuaName} = new(\"{m.LuaName}\", (context, ct) =>");
            W(sb, i, "{");
            var b = i + 1;
            W(sb, b, $"var userData = context.GetArgument<{TypeRef(_type.FullTypeName)}>(0);");
            for (var pi = 0; pi < m.Parameters.Length; pi++)
                W(sb, b, $"var arg{pi} = context.GetArgument<{Ts(m.Parameters[pi])}>({pi + 1});");
            var args = string.Join(", ", Enumerable.Range(0, m.Parameters.Length).Select(pi =>
                m.Parameters[pi].NeedsStructUserData ? $"arg{pi}.Value" : $"arg{pi}"));

            if (m.IsExtension)
            {
                var callArgs = args.Length > 0 ? $"userData, {args}" : "userData";
                if (ret) { W(sb, b, $"{m.DeclaringType}.{m.Name}({callArgs});"); W(sb, b, "return new System.Threading.Tasks.ValueTask<int>(context.Return());"); }
                else { W(sb, b, $"var __result = {m.DeclaringType}.{m.Name}({callArgs});"); W(sb, b, $"return new System.Threading.Tasks.ValueTask<int>(context.Return({WrRet("__result", m)}));"); }
            }
            else
            {
                if (ret) { W(sb, b, $"userData.{m.Name}({args});"); W(sb, b, "return new System.Threading.Tasks.ValueTask<int>(context.Return());"); }
                else { W(sb, b, $"var __result = userData.{m.Name}({args});"); W(sb, b, $"return new System.Threading.Tasks.ValueTask<int>(context.Return({WrRet("__result", m)}));"); }
            }
            W(sb, i, "}");
            W(sb, i, ");");
            sb.AppendLine();
        }
    }

    // ---------------------------------------------------------------
    // Events
    // ---------------------------------------------------------------
    private void Events(CodeBuilder sb, int i)
    {
        foreach (var evt in _type.InstanceEvents)
        {
            W(sb, i, $"internal static readonly global::Lua.LuaFunction __function_{evt.Name}_add = new(\"add_{evt.LuaName}\", (context, ct) =>");
            W(sb, i, "{");
            W(sb, i + 1, $"var userData = context.GetArgument<{TypeRef(_type.FullTypeName)}>(0);");
            W(sb, i + 1, "return new System.Threading.Tasks.ValueTask<int>(context.Return());");
            W(sb, i, "}"); W(sb, i, ");"); sb.AppendLine();
            W(sb, i, $"internal static readonly global::Lua.LuaFunction __function_{evt.Name}_remove = new(\"remove_{evt.LuaName}\", (context, ct) =>");
            W(sb, i, "{"); W(sb, i + 1, "return new System.Threading.Tasks.ValueTask<int>(context.Return());");
            W(sb, i, "}"); W(sb, i, ");"); sb.AppendLine();
        }
    }

    // ---------------------------------------------------------------
    // __index — inherited methods reference base/interface impl
    // ---------------------------------------------------------------
    private void Index(CodeBuilder sb, int i)
    {
        W(sb, i, "internal static readonly global::Lua.LuaFunction __metamethod_index = new(\"index\", (context, ct) =>");
        W(sb, i, "{"); var b = i + 1;
        W(sb, b, $"var userData = context.GetArgument<{TypeRef(_type.FullTypeName)}>(0);");
        W(sb, b, "var key = context.GetArgument(1);");
        W(sb, b, "if (key.TryRead<string>(out var stringKey))");
        W(sb, b, "{"); var body = b + 1;
        foreach (var f in _type.InstanceFields) W(sb, body, $"if (stringKey == \"{f.LuaName}\") return new System.Threading.Tasks.ValueTask<int>(context.Return({WrField("userData." + f.Name, f.FieldType)}));");
        foreach (var p in _type.InstanceProperties.Where(x => x.HasGetter)) W(sb, body, $"if (stringKey == \"{p.LuaName}\") return new System.Threading.Tasks.ValueTask<int>(context.Return({WrField("userData." + p.Name, p.PropertyType)}));");
        var seenMethods = new HashSet<string>();
        foreach (var m in _type.InstanceMethods)
        {
            if (!seenMethods.Add(m.FullLuaName)) continue;
            if (m.IsInherited)
                W(sb, body, $"if (stringKey == \"{m.FullLuaName}\") return new System.Threading.Tasks.ValueTask<int>(context.Return(new global::Lua.LuaValue({m.ImplementationSourceType}.__Cache.__function_{m.FullLuaName})));");
            else
                W(sb, body, $"if (stringKey == \"{m.FullLuaName}\") return new System.Threading.Tasks.ValueTask<int>(context.Return(new global::Lua.LuaValue(__Cache.__function_{m.FullLuaName})));");
        }
        foreach (var evt in _type.InstanceEvents) { W(sb, body, $"if (stringKey == \"add_{evt.LuaName}\") return new System.Threading.Tasks.ValueTask<int>(context.Return(new global::Lua.LuaValue(__Cache.__function_{evt.Name}_add)));"); W(sb, body, $"if (stringKey == \"remove_{evt.LuaName}\") return new System.Threading.Tasks.ValueTask<int>(context.Return(new global::Lua.LuaValue(__Cache.__function_{evt.Name}_remove)));"); }
        W(sb, body, "return new System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.Nil));");
        W(sb, b, "}");

        if (_type.IsInlineArray && _type.InlineArrayLength.HasValue)
        {
            W(sb, b, "if (key.TryRead<double>(out var num) && double.IsFinite(num) && num >= 1.0 && num <= int.MaxValue)");
            W(sb, b, "{"); W(sb, body, "var index = (int)num - 1;"); W(sb, body, $"if ((uint)index < (uint){_type.InlineArrayLength.Value})");
            W(sb, body, "{");
            var et = _type.InlineArrayElementType ?? "byte";
            W(sb, body + 1, $"ref var element = ref System.Runtime.CompilerServices.Unsafe.Add(ref System.Runtime.CompilerServices.Unsafe.As<{TypeRef(_type.FullTypeName)}, {et}>(ref userData), index);");
            W(sb, body + 1, "return new System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.FromObject(element)));");
            W(sb, body, "}"); W(sb, b, "}");
        }
        W(sb, b, "return new System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.Nil));");
        W(sb, i, "}"); W(sb, i, ");"); sb.AppendLine();
    }

    // ---------------------------------------------------------------
    // __newindex
    // ---------------------------------------------------------------
    private void NewIndex(CodeBuilder sb, int i)
    {
        W(sb, i, "internal static readonly global::Lua.LuaFunction __metamethod_newindex = new(\"newindex\", (context, ct) =>");
        W(sb, i, "{"); var b = i + 1;
        W(sb, b, $"var userData = context.GetArgument<{TypeRef(_type.FullTypeName)}>(0);");
        W(sb, b, "var key = context.GetArgument(1);");
        W(sb, b, "if (key.TryRead<string>(out var stringKey))");
        W(sb, b, "{"); var body = b + 1;
        foreach (var f in _type.InstanceFields.Where(x => !x.IsReadOnly))
        {
            W(sb, body, $"if (stringKey == \"{f.LuaName}\")");
            W(sb, body, "{");
            if (IsNullable(f.FieldType))
                WriteNullableSetter(sb, body + 1, $"userData.{f.Name}", f.FieldType);
            else
            {
                W(sb, body + 1, $"userData.{f.Name} = context.GetArgument<{TsType(f.FieldType)}>(2);");
                W(sb, body + 1, "return new System.Threading.Tasks.ValueTask<int>(context.Return());");
            }
            W(sb, body, "}");
        }
        foreach (var p in _type.InstanceProperties.Where(x => x.HasSetter))
        {
            W(sb, body, $"if (stringKey == \"{p.LuaName}\")");
            W(sb, body, "{");
            if (IsNullable(p.PropertyType))
                WriteNullableSetter(sb, body + 1, $"userData.{p.Name}", p.PropertyType);
            else
            {
                W(sb, body + 1, $"userData.{p.Name} = context.GetArgument<{TsType(p.PropertyType)}>(2);");
                W(sb, body + 1, "return new System.Threading.Tasks.ValueTask<int>(context.Return());");
            }
            W(sb, body, "}");
        }
        W(sb, body, "throw new global::Lua.LuaRuntimeException(context.State, $\"'{stringKey}' not found.\");");
        W(sb, b, "}"); W(sb, b, "throw new global::Lua.LuaRuntimeException(context.State, $\"'{key}' not found.\");");
        W(sb, i, "}"); W(sb, i, ");"); sb.AppendLine();
    }

    // ---------------------------------------------------------------
    // __tostring
    // ---------------------------------------------------------------
    private void Tostring(CodeBuilder sb, int i)
    {
        W(sb, i, "internal static readonly global::Lua.LuaFunction __metamethod_tostring = new(\"tostring\", (context, ct) =>");
        W(sb, i, "{");
        W(sb, i + 1, $"var userData = context.GetArgument<{TypeRef(_type.FullTypeName)}>(0);");
        W(sb, i + 1, $"return new System.Threading.Tasks.ValueTask<int>(context.Return($\"{_type.TypeName}: {{userData}}\"));");
        W(sb, i, "}");
        W(sb, i, ");");
        sb.AppendLine();
    }

    // ---------------------------------------------------------------
    // Metatable property
    // ---------------------------------------------------------------
    private void Metatable(CodeBuilder sb, int i)
    {
        W(sb, i, "static global::Lua.LuaTable? Metatable");
        W(sb, i, "{"); var b = i + 1;
        W(sb, b, "get"); W(sb, b, "{"); var gb = b + 1;
        W(sb, gb, "if (__Cache.__metatable != null) return __Cache.__metatable;"); sb.AppendLine();
        W(sb, gb, "__Cache.__metatable = new();");
        if (!_type.IsStatic)
        {
            W(sb, gb, "__Cache.__metatable[global::Lua.Runtime.Metamethods.Index] = __Cache.__metamethod_index;");
            W(sb, gb, "__Cache.__metatable[global::Lua.Runtime.Metamethods.NewIndex] = __Cache.__metamethod_newindex;");
            W(sb, gb, "__Cache.__metatable[global::Lua.Runtime.Metamethods.ToString] = __Cache.__metamethod_tostring;");
            foreach (var m in _type.InstanceMethods.Where(m => !m.IsInherited))
                W(sb, gb, $"__Cache.__metatable[\"{m.FullLuaName}\"] = new global::Lua.LuaValue(__Cache.__function_{m.FullLuaName});");
            foreach (var evt in _type.InstanceEvents) { W(sb, gb, $"__Cache.__metatable[\"add_{evt.LuaName}\"] = new global::Lua.LuaValue(__Cache.__function_{evt.Name}_add);"); W(sb, gb, $"__Cache.__metatable[\"remove_{evt.LuaName}\"] = new global::Lua.LuaValue(__Cache.__function_{evt.Name}_remove);"); }
        }
        W(sb, gb, "return __Cache.__metatable;");
        W(sb, b, "}"); W(sb, b, "set => throw new System.InvalidOperationException(\"The metatable of a [LuaVisible] type cannot be replaced.\");");
        W(sb, i, "}"); sb.AppendLine();
    }

    private void Explicit(CodeBuilder sb, int i)
    {
        W(sb, i, "global::Lua.LuaTable? global::Lua.ILuaUserData.Metatable");
        W(sb, i, "{"); W(sb, i + 1, "get => Metatable;"); W(sb, i + 1, "set => Metatable = value;");
        W(sb, i, "}"); sb.AppendLine();
    }

    private void Operator(CodeBuilder sb, int i)
    {
        if (_type.IsInterface) return;
        if (_type.IsStatic) return;
        W(sb, i, $"public static implicit operator global::Lua.LuaValue({_type.TypeName} value)");
        W(sb, i, "{"); W(sb, i + 1, "return global::Lua.LuaValue.FromUserData(value);"); W(sb, i, "}");
    }

    // ---------------------------------------------------------------
    // TypeTable (static members + constructors)
    // ---------------------------------------------------------------
    private void TypeTable(CodeBuilder sb, int i)
    {
        var hasStatic = _type.StaticMethods.Length > 0 || _type.StaticProperties.Length > 0
            || _type.StaticFields.Length > 0 || _type.Constructors.Length > 0 || _type.StaticEvents.Length > 0
            || _type.IsValueType || (!_type.IsStatic && !_type.IsInterface); // non-static, non-interface types get default new()
        if (!hasStatic) return;

        W(sb, i, "public static global::Lua.LuaTable TypeTable");
        W(sb, i, "{"); var b = i + 1;
        W(sb, b, "get"); W(sb, b, "{"); var gb = b + 1;
        W(sb, gb, "if (__Cache.__typeTable != null) return __Cache.__typeTable;"); sb.AppendLine();
        W(sb, gb, "__Cache.__typeTable = new();");

        if (_type.Constructors.Length > 0)
        {
            foreach (var c in _type.Constructors)
                W(sb, gb, $"__Cache.__typeTable[\"{c.FullLuaNew}\"] = new global::Lua.LuaValue(__Cache.__function_new{c.OverloadSuffix});");
        }
        else if (!_type.IsStatic && !_type.IsInterface)
            W(sb, gb, $"__Cache.__typeTable[\"new\"] = new global::Lua.LuaValue(new global::Lua.LuaFunction(\"new\", (context, ct) => new System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.FromUserData(new {_type.FullTypeName}())))));");

        foreach (var m in _type.StaticMethods)
        {
            W(sb, gb, $"__Cache.__typeTable[\"{m.FullLuaName}\"] = new global::Lua.LuaValue(__Cache.__function_static_{m.FullLuaName});");
        }

        foreach (var evt in _type.StaticEvents)
            W(sb, gb, $"__Cache.__typeTable[\"add_{evt.LuaName}\"] = new global::Lua.LuaValue(new global::Lua.LuaFunction(\"add_{evt.LuaName}\", (context, ct) => new System.Threading.Tasks.ValueTask<int>(context.Return())));");

        if (_type.StaticProperties.Length > 0 || _type.StaticFields.Length > 0)
        {
            W(sb, gb, "var __si = new global::Lua.LuaFunction(\"__index\", (context, ct) =>");
            W(sb, gb, "{");
            W(sb, gb + 1, "var key = context.GetArgument(1);");
            W(sb, gb + 1, "if (key.TryRead<string>(out var sk))");
            W(sb, gb + 1, "{");
            foreach (var f in _type.StaticFields)
                W(sb, gb + 2, $"if (sk == \"{f.LuaName}\") return new System.Threading.Tasks.ValueTask<int>(context.Return({WrField($"{_type.FullTypeName}.{f.Name}", f.FieldType)}));");
            foreach (var p in _type.StaticProperties.Where(x => x.HasGetter))
                W(sb, gb + 2, $"if (sk == \"{p.LuaName}\") return new System.Threading.Tasks.ValueTask<int>(context.Return({WrField($"{_type.FullTypeName}.{p.Name}", p.PropertyType)}));");
            W(sb, gb + 1, "}");
            W(sb, gb + 1, "return new System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.Nil));");
            W(sb, gb, "});");

            var hasWritable = _type.StaticFields.Any(f => !f.IsReadOnly) || _type.StaticProperties.Any(p => p.HasSetter);
            // Create a metatable for the TypeTable so __index/__newindex work via Lua's metatable mechanism
            W(sb, gb, "var __typeMt = new global::Lua.LuaTable(0, " + (hasWritable ? "2" : "1") + ");");
            W(sb, gb, "__typeMt[global::Lua.Runtime.Metamethods.Index] = new global::Lua.LuaValue(__si);");
            if (hasWritable)
            {
                W(sb, gb, "var __sni = new global::Lua.LuaFunction(\"__newindex\", (context, ct) =>");
                W(sb, gb, "{");
                W(sb, gb + 1, "var key = context.GetArgument(1);");
                W(sb, gb + 1, "var val = context.GetArgument(2);");
                W(sb, gb + 1, "if (key.TryRead<string>(out var sk))");
                W(sb, gb + 1, "{");
                foreach (var f in _type.StaticFields.Where(x => !x.IsReadOnly))
                {
                    if (IsNullable(f.FieldType))
                        W(sb, gb + 2, $"if (sk == \"{f.LuaName}\") {{ {_type.FullTypeName}.{f.Name} = val.Type == global::Lua.LuaValueType.Nil ? ({f.FieldType})null : val.Read<{NullableUnderlying(f.FieldType)}>(); return new System.Threading.Tasks.ValueTask<int>(context.Return()); }}");
                    else
                        W(sb, gb + 2, $"if (sk == \"{f.LuaName}\") {{ {_type.FullTypeName}.{f.Name} = val.Read<{TsType(f.FieldType)}>(); return new System.Threading.Tasks.ValueTask<int>(context.Return()); }}");
                }
                foreach (var p in _type.StaticProperties.Where(x => x.HasSetter))
                {
                    if (IsNullable(p.PropertyType))
                        W(sb, gb + 2, $"if (sk == \"{p.LuaName}\") {{ {_type.FullTypeName}.{p.Name} = val.Type == global::Lua.LuaValueType.Nil ? ({p.PropertyType})null : val.Read<{NullableUnderlying(p.PropertyType)}>(); return new System.Threading.Tasks.ValueTask<int>(context.Return()); }}");
                    else
                        W(sb, gb + 2, $"if (sk == \"{p.LuaName}\") {{ {_type.FullTypeName}.{p.Name} = val.Read<{TsType(p.PropertyType)}>(); return new System.Threading.Tasks.ValueTask<int>(context.Return()); }}");
                }
                W(sb, gb + 1, "}");
                W(sb, gb + 1, "throw new global::Lua.LuaRuntimeException(context.State, $\"'{sk}' is read-only or not found.\");");
                W(sb, gb, "});");
                W(sb, gb, "__typeMt[global::Lua.Runtime.Metamethods.NewIndex] = new global::Lua.LuaValue(__sni);");
            }
            W(sb, gb, "__Cache.__typeTable.Metatable = __typeMt;");
        }

        W(sb, gb, "return __Cache.__typeTable;");
        W(sb, b, "}"); W(sb, i, "}"); sb.AppendLine();
    }

    // ------------------------------------------------------------------
    // Type helpers
    // ------------------------------------------------------------------
    private static void W(CodeBuilder sb, int i, string line) => sb.AppendLineIndented(line, i);

    /// <summary>Type reference for GetArgument — uses StructUserData if type is external.</summary>
    private static string TypeRef(string t) => t;

    /// <summary>Stack type for parameter — wraps in StructUserData if needed.</summary>
    private static string Ts(LuaParameterMetadata p) =>
        p.NeedsStructUserData ? $"nfm_world_library.Lua.StructUserData<{p.Type}>" : TsType(p.Type);

    /// <summary>Stack type for a raw type string.</summary>
    private static string TsType(string t) => t switch
    {
        "int" => "int", "long" => "long", "float" => "float", "double" => "double",
        "bool" => "bool", "string" => "string", "object" => "object", "void" => "void",
        "byte" => "byte", "sbyte" => "sbyte", "short" => "short", "ushort" => "ushort",
        "uint" => "uint", "ulong" => "ulong", "decimal" => "decimal",
        "int?" => "int?", "long?" => "long?", "float?" => "float?", "double?" => "double?",
        "bool?" => "bool?", _ => t
    };

    /// <summary>Wrap return value for a method.</summary>
    private string WrRet(string expr, LuaMethodMetadata m)
    {
        if (m.ReturnType == "void") return expr;
        if (IsSimple(m.ReturnType) && !IsNullable(m.ReturnType)) return $"({expr})";
        if (IsSimple(m.ReturnType) && IsNullable(m.ReturnType)) return WrNullableValue(expr, m.ReturnType);
        if (IsKnownLuaVisible(m.ReturnType)) return $"global::Lua.LuaValue.FromUserData({expr})";
        if (NeedsStructWrap(m.ReturnType))
        {
            var mtRef = GetMetatableRef(m.ReturnType);
            return $"global::Lua.LuaValue.FromUserData(new nfm_world_library.Lua.StructUserData<{m.ReturnType}>({mtRef}) {{ Value = {expr} }})";
        }
        // Fallback: use FromObject for complex/generic types that don't implement ILuaUserData
        return $"global::Lua.LuaValue.FromObject({expr})";
    }

    /// <summary>Wrap field/property return value.</summary>
    private string WrField(string expr, string rt)
    {
        if (rt == "void") return expr;
        if (IsSimple(rt) && !IsNullable(rt)) return $"({expr})";
        if (IsSimple(rt) && IsNullable(rt)) return WrNullableValue(expr, rt);
        if (IsKnownLuaVisible(rt)) return $"global::Lua.LuaValue.FromUserData({expr})";
        if (NeedsStructWrap(rt))
        {
            var mtRef = GetMetatableRef(rt);
            return $"global::Lua.LuaValue.FromUserData(new nfm_world_library.Lua.StructUserData<{rt}>({mtRef}) {{ Value = {expr} }})";
        }
        // Fallback: use FromObject for complex/generic types that don't implement ILuaUserData
        return $"global::Lua.LuaValue.FromObject({expr})";
    }

    /// <summary>Generate "value or nil" marshalling for Nullable&lt;T&gt; types.</summary>
    private static string WrNullableValue(string expr, string nullableType)
    {
        // Extract underlying type: "int?" → "int"
        var underlying = NullableUnderlying(nullableType);
        // Value types: HasValue ? cast-to-LuaValue(Value) : Nil
        // Numeric types go through double; bool uses explicit LuaValue(bool)
        if (underlying == "bool")
            return $"{expr}.HasValue ? new global::Lua.LuaValue({expr}.Value) : global::Lua.LuaValue.Nil";
        // All other value types (int, long, float, double, byte, etc.) → cast via double
        return $"{expr}.HasValue ? (global::Lua.LuaValue)(double){expr}.Value : global::Lua.LuaValue.Nil";
    }

    /// <summary>Generate nil→null setter for a nullable field/property write.</summary>
    private static void WriteNullableSetter(CodeBuilder sb, int indent, string targetExpr, string nullableType)
    {
        var underlying = NullableUnderlying(nullableType);
        W(sb, indent, "var __val = context.GetArgument(2);");
        W(sb, indent, $"if (__val.Type == global::Lua.LuaValueType.Nil) {{ {targetExpr} = null; return new System.Threading.Tasks.ValueTask<int>(context.Return()); }}");
        W(sb, indent, $"{targetExpr} = __val.Read<{underlying}>();");
        W(sb, indent, "return new System.Threading.Tasks.ValueTask<int>(context.Return());");
    }

    private static bool IsNullable(string t) => t.EndsWith("?");

    private static string NullableUnderlying(string t) =>
        t.EndsWith("?") ? t.Substring(0, t.Length - 1) : t;

    private bool IsKnownLuaVisible(string fullTypeName)
    {
        return _knownLuaVisibleFullNames.Contains(fullTypeName);
    }

    private static string GetMetatableRef(string typeName)
    {
        // Skip true tuple types
        var baseName = typeName.Contains('<') ? typeName.Substring(0, typeName.IndexOf('<')) : typeName;
        if (baseName.StartsWith("(") || baseName == "System.ValueTuple" || baseName == "System.Tuple")
            return "null";
        // Simple types that don't need StructUserData wrapping — no metatable needed
        if (!NeedsStructWrap(typeName))
            return "null";
        // Try to match a generated metatable by sanitized name
        var safe = Sanitize(typeName);
        return $"StructUserData_Metatable_{safe}.Metatable";
    }

    private static bool IsSimple(string t) => t switch
    {
        "int" or "long" or "float" or "double" or "bool" or "string" or "object"
            or "byte" or "sbyte" or "short" or "ushort" or "uint" or "ulong" or "decimal" or "char" => true,
        "int?" or "long?" or "float?" or "double?" or "bool?"
            or "byte?" or "sbyte?" or "short?" or "ushort?" or "uint?" or "ulong?" or "decimal?" or "char?" => true,
        _ => IsFixedMathType(t)
    };

    /// <summary>Check if t is a FixedMath type (not just contains it — avoids false positives on generics).</summary>
    private static bool IsFixedMathType(string t)
    {
        // Strip generic arguments to check only the outermost type
        var baseT = t.Contains('<') ? t.Substring(0, t.IndexOf('<')) : t;
        return baseT == "FixedMathSharp.Fixed64" || baseT == "Fixed64"
            || baseT == "FixedMathSharp.Vector3d" || baseT == "Vector3d"
            || baseT == "FixedMathSharp.f64AngleSingle" || baseT == "f64AngleSingle"
            || baseT == "FixedMathSharp.f64Euler" || baseT == "f64Euler"
            || baseT == "FixedMathSharp.Fixed4x4" || baseT == "Fixed4x4";
    }

    private static bool NeedsStructWrap(string t)
    {
        if (IsSimple(t)) return false;
        // Only skip true tuple types — check outermost type name (before any '<')
        var baseName = t.Contains('<') ? t.Substring(0, t.IndexOf('<')) : t;
        if (baseName.StartsWith("(") || baseName == "System.ValueTuple" || baseName == "System.Tuple")
            return false;
        return true;
    }

    private static string Sanitize(string name) =>
        name.Replace("global::", "").Replace("[]", "Array")
            .Replace("<", "_").Replace(">", "_")
            .Replace("(", "_").Replace(")", "_")
            .Replace("[", "_").Replace("]", "_").Replace("*", "Ptr_")
            .Replace("?", "_Nullable").Replace(",", "_")
            .Replace(" ", "").Replace(".", "_");
}
