using WorldXaml.Generator.Common;

namespace NFMWorld.LuaSourceGenerator;

internal sealed class LuaBindingInitGenerator(
    IReadOnlyList<BaseLuaTypeMetadata> types
) : BaseLuaTypeGenerator
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine();
        sb.AppendLine("namespace NFMWorld.LuaSourceGenerator.Generator");
        using (sb.Block())
        {
            sb.AppendLine("partial class GeneratorGenerated");
            using (sb.Block())
            {
                EmitNamespaceTreeInit(sb, CollectNamespaceTables());

                sb.AppendLine("static GeneratorGenerated()");
                using (sb.Block())
                {
                    foreach (var type in types)
                    {
                        if (!type.IsStatic)
                        {
                            sb.AppendLine($"init_{GetMetatableName(type)}();");
                            sb.AppendLine($"global::NFMWorld.LuaSourceGenerator.Generator.LuaVisibleTypeMetatableRegistry<{type.FullTypeName}>.Register({GetMetatableName(type)});");
                        }

                        sb.AppendLine($"init_{GetTypeTableName(type)}();");
                    }

                    sb.AppendLine("init_Namespaces();");
                }
            }

            sb.AppendLine("public static class LuaVisibleTypeRegistry");
            using (sb.Block())
            {
                EmitRegisterAll(sb);
            }
            
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Thread-safe registry mapping each <typeparamref name=\"T\"/> to its code-generated StructUserData metatable.");
            sb.AppendLine("/// Populated at assembly load time by the source-generated <see cref=\"StructUserDataMetatableInitializer\"/>.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public static class LuaVisibleTypeMetatableRegistry<T>");
            using (sb.Block())
            {
                sb.AppendLine("public static global::Lua.LuaTable? Metatable { get; private set; }");
                sb.AppendLine("internal static void Register(global::Lua.LuaTable metatable) => Metatable = metatable;");
            }
        }

        //
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        return sb.ToString();
    }
    
    private static void EmitRegisterAll(IndentedStringBuilder sb)
    {
        sb.AppendLine("public static void RegisterAll(global::Lua.LuaState state)");
        using (sb.Block())
        {
            sb.AppendLine("foreach (var (k, v) in global::NFMWorld.LuaSourceGenerator.Generator.GeneratorGenerated.__namespaceTable_G)");
            using (sb.Block())
            {
                sb.AppendLine("state.Environment[k] = v;");
            }
        }
    }

    // ================================================================
    // Trie node — one per unique namespace path
    // ================================================================

    private sealed class NamespaceNode
    {
        /// <summary>Lua key for this segment, e.g. "TestFixtures" ("" for the root).</summary>
        public string Segment = "";
        /// <summary>Dot-joined path from the root, e.g. "NFMWorld.LuaSourceGenerator".</summary>
        public string Path = "";
        public SortedDictionary<string, NamespaceNode> Children { get; } = new(StringComparer.Ordinal);
        /// <summary>Types living directly in this namespace.</summary>
        public List<BaseLuaTypeMetadata> Types { get; } = [];
    }

    // ================================================================
    // 1) Collect: build the trie from all types' namespaces
    // ================================================================

    private string GetNamespace(BaseLuaTypeMetadata type)
    {
        return type.LuaName[..(type.LuaName.LastIndexOf('.') is var v and not -1 ? v : 0)];
    }

    private string GetLeaf(BaseLuaTypeMetadata type)
    {
        return type.LuaName[(type.LuaName.LastIndexOf('.') + 1)..];
    }
    
    private NamespaceNode CollectNamespaceTables()
    {
        var root = new NamespaceNode();

        // Only real types participate — stub types have no type table to register.
        foreach (var type in types)
        {
            var node = root;

            if (!string.IsNullOrEmpty(GetNamespace(type)))
            {
                foreach (var segment in type.Namespace.Split('.', StringSplitOptions.RemoveEmptyEntries))
                {
                    if (!node.Children.TryGetValue(segment, out var child))
                    {
                        node.Children[segment] = child = new NamespaceNode
                        {
                            Segment = segment,
                            Path = node.Path.Length == 0
                                ? segment
                                : node.Path + "." + segment,
                        };
                    }
                    node = child;
                }
            }

            node.Types.Add(type); // global namespace → lands on the root
        }

        return root;
    }

    // ================================================================
    // 2) Emit: fields + init with ??= dedup, depth-first
    // ================================================================

    private static string FieldName(NamespaceNode node)
        => $"__namespaceTable_{ToIdentifier(node.Path)}";

    private static IEnumerable<NamespaceNode> EnumerateNodes(NamespaceNode node)
    {
        foreach (var child in node.Children.Values)
        {
            yield return child;
            foreach (var descendant in EnumerateNodes(child))
                yield return descendant;
        }
    }

    private void EmitNamespaceTreeInit(IndentedStringBuilder sb, NamespaceNode root)
    {
        // Field declarations — one per unique namespace path (deterministic order)
        foreach (var node in EnumerateNodes(root))
            sb.AppendLine($"internal static global::Lua.LuaTable {FieldName(node)} = null!;");

        sb.AppendLine("internal static global::System.Collections.Generic.Dictionary<string, global::Lua.LuaTable> __namespaceTable_G = null!;");
        sb.AppendLine();

        sb.AppendLine("internal static void init_Namespaces()");
        using (sb.Block())
        {
            sb.AppendLine($"__namespaceTable_G ??= new global::System.Collections.Generic.Dictionary<string, global::Lua.LuaTable>();");
            EmitNode(sb, root, "__namespaceTable_G");
        }
    }

    private void EmitNode(IndentedStringBuilder sb, NamespaceNode node, string parentExpr)
    {
        // Child namespace tables: null-check + create, then attach via set indexer
        foreach (var child in node.Children.Values)
        {
            var field = FieldName(child);
            sb.AppendLine(
                $"{field} ??= new global::Lua.LuaTable(0, {child.Children.Count + child.Types.Count});");
            sb.AppendLine($"{parentExpr}[\"{child.Segment}\"] = {field};");
        }

        // Types directly in this namespace: attach their type tables
        foreach (var type in node.Types)
        {
            sb.AppendLine($"{parentExpr}[\"{GetLeaf(type)}\"] = {GetTypeTableName(type)};");
        }

        // Recurse (depth-first keeps child tables attached before grandchildren fill them)
        foreach (var child in node.Children.Values)
            EmitNode(sb, child, FieldName(child));
    }
}