<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <AnalyzerLanguage>cs</AnalyzerLanguage>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <DevelopmentDependency>true</DevelopmentDependency>
        <IncludeSymbols>false</IncludeSymbols>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
        <IsRoslynComponent>true</IsRoslynComponent>
        <RootNamespace>NFMWorld.LuaSourceGenerator</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="LuaVisibleGenerator_StubsOutputDirectory" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0" PrivateAssets="all" />
        <PackageReference Include="PolySharp" Version="1.14.1" PrivateAssets="all" />
        <PackageReference Include="System.IO.FileSystem" Version="4.3.0" PrivateAssets="all" />
    </ItemGroup>

</Project>
