<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <AnalyzerLanguage>cs</AnalyzerLanguage>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <DevelopmentDependency>true</DevelopmentDependency>
        <IncludeSymbols>false</IncludeSymbols>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
        <IsRoslynComponent>true</IsRoslynComponent>
        <RootNamespace>NFMWorld.LuaSourceGenerator</RootNamespace>
        <PolyStringInterpolation>true</PolyStringInterpolation>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="LuaVisibleGenerator_StubsOutputDirectory" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0" PrivateAssets="all" />
        <PackageReference Include="Polyfill" Version="10.5.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.IO.FileSystem" Version="4.3.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)/$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="IndentedStringBuilder.cs">
        <LinkBase>Compiler/XamlX.IL.CSharp\</LinkBase>
        <Link>Compiler\XamlX.IL.CSharp\IndentedStringBuilder.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
