global using Vector3 = Microsoft.Xna.Framework.Vector3;
global using Int3 = Stride.Core.Mathematics.Int3;
global using Color3 = nfm_world_library.util.Color3;
global using Quaternion = Microsoft.Xna.Framework.Quaternion;
global using Matrix = Microsoft.Xna.Framework.Matrix;
global using AngleSingle = Stride.Core.Mathematics.AngleSingle;
global using Vector2 = Microsoft.Xna.Framework.Vector2;
global using URandom = nfm_world_library.util.Random;
global using LuaJIT;
global using static LuaJIT.Methods;
global using Color = Microsoft.Xna.Framework.Color;
global using RectangleF = Stride.Core.Mathematics.RectangleF;
global using static nfm_world_library.TheVFS;
global using static nfm_world_library.mad.Lua;