using System;
using System.IO;
using Microsoft.CodeAnalysis;
using WorldXaml.Generator.Common;

namespace NFMWorld.ShaderSourceGen;

[Generator(LanguageNames.CSharp)]
public class FnaShaderIncrementalGenerator : IIncrementalGenerator
{
    private const string SourceItemGroupMetadata = "build_metadata.AdditionalFiles.SourceItemGroup";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var options = context.AnalyzerConfigOptionsProvider
            .WithTrackingName("AnalyzerConfigOptionsProvider");

        var effectFiles = context.AdditionalTextsProvider
            .Combine(options)
            .Where(static pair =>
            {
                var (text, options) = pair;
                
                var filePath = text.Path;
                if (!filePath.EndsWith(".fx", StringComparison.OrdinalIgnoreCase))
                {
                    return false;
                }

                if (!options.GetOptions(pair.Left).TryGetValue(SourceItemGroupMetadata, out var itemGroup)
                    || itemGroup != "FnaEffect")
                {
                    return false;
                }

                return true;
            })
            .Select(static (pair, _) => pair.Left)
            .WithTrackingName("EffectFiles");

        context.RegisterSourceOutput(effectFiles, static (context, text) =>
        {
            var path = text.Path;
            var sourceText = text.GetText();
            var effectName = Path.GetFileNameWithoutExtension(path) + "Effect";

            var sb = new IndentedStringBuilder();
                
            var shaderDir = Path.GetDirectoryName(path);
            var pp = new HLSLPreprocessor(
                predefined: [],
#pragma warning disable RS1035
                includeResolver: path => File.ReadAllText(Path.Combine(shaderDir ?? "", path))
#pragma warning restore RS1035
            );
            var processedShader = pp.Process(sourceText?.ToString() ?? string.Empty, path);
                
            sb.AppendLine("/*");
            sb.AppendLine(processedShader);
            sb.AppendLine("*/");

            try
            {
                var parser = new HLSLParser(path, processedShader);
                var tree = new HLSLTree();
                
                if (!parser.Parse(tree))
                {
                    sb.AppendLine("// Failed to parse HLSL file:");
                }

                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("#nullable enable");
                sb.AppendLine();
                sb.AppendLine("using NFMWorld.Graphics;");
                sb.AppendLine("using NFMWorld.Graphics.FNA3D;");
                sb.AppendLine("using NFMWorld.Shaders;");
                sb.AppendLine();
                sb.AppendLine("namespace NFMWorld.Shaders.Generated;");
                sb.AppendLine();

                // The shader module (compiled Effect blob) is backend-specific but has no
                // per-pipeline state of its own - it's just bytecode, loaded once and reused by
                // every pipeline built from it. Uniform *slots*, in contrast, are only knowable
                // once a pipeline's reflection exists (see IPipelineState.Reflection's doc
                // comment: FNA3D can only reflect an Effect blob's parameters after parsing it
                // against a live device), so those live on a separate, pipeline-bound type built
                // via Bind() rather than on the module itself.
                sb.AppendLine($"internal sealed class {effectName}");
                sb.AppendLine("{");
                using (sb.Indent())
                {
                    sb.AppendLine("public IShaderModule Module { get; }");
                    sb.AppendLine();
                    sb.AppendLine($"public {effectName}(byte[] effectCode)");
                    sb.AppendLine("{");
                    using (sb.Indent())
                    {
                        sb.AppendLine("Module = FNA3DGraphicsDevice.LoadEffectModule(effectCode);");
                    }
                    sb.AppendLine("}");
                    sb.AppendLine();
                    sb.AppendLine("/// <summary>");
                    sb.AppendLine("/// Resolves this shader's uniform slots against an already-built pipeline's reflection.");
                    sb.AppendLine("/// Call once when the pipeline is created - not per frame or per draw - and reuse the");
                    sb.AppendLine("/// result, since slots are stable for the pipeline's lifetime.");
                    sb.AppendLine("/// </summary>");
                    sb.AppendLine($"public {effectName}Parameters Bind(IPipelineState pipeline) => new(pipeline.Reflection);");
                }
                sb.AppendLine("}");
                sb.AppendLine();

                sb.AppendLine($"internal readonly struct {effectName}Parameters");
                sb.AppendLine("{");
                using (sb.Indent())
                {
                    sb.AppendLine($"internal {effectName}Parameters(ShaderReflection reflection)");
                    sb.AppendLine("{");
                    using (sb.Indent())
                    {
                        foreach (var statement in tree.Root.Statements())
                        {
                            if (statement is HLSLDeclaration declaration)
                            {
                                if (declaration.Type.BaseType is HLSLBaseType.Sampler or HLSLBaseType.Sampler2D or HLSLBaseType.SamplerCube)
                                    continue;

                                sb.AppendLine($"{declaration.Name} = new {declaration.Type.BaseType}EffectParameter(SlotOf(reflection, \"{declaration.Name}\"));");
                            }
                        }
                    }
                    sb.AppendLine("}");
                    sb.AppendLine();

                    foreach (var statement in tree.Root.Statements())
                    {
                        if (statement is HLSLDeclaration declaration)
                        {
                            if (declaration.Type.BaseType is HLSLBaseType.Sampler or HLSLBaseType.Sampler2D or HLSLBaseType.SamplerCube)
                                continue;

                            sb.AppendLine($"public {declaration.Type.BaseType}EffectParameter {declaration.Name} {{ get; }}");
                        }
                    }

                    sb.AppendLine();
                    sb.AppendLine("// -1 (\"not found\") mirrors the old FNA model's \"parameter != null\" check for a");
                    sb.AppendLine("// uniform the HLSL compiler optimized out - every *EffectParameter.SetValue below");
                    sb.AppendLine("// no-ops on a negative slot.");
                    sb.AppendLine("private static int SlotOf(ShaderReflection reflection, string name)");
                    sb.AppendLine("{");
                    using (sb.Indent())
                    {
                        sb.AppendLine("foreach (var uniform in reflection.Uniforms)");
                        sb.AppendLine("{");
                        using (sb.Indent())
                        {
                            sb.AppendLine("if (uniform.Name == name) return uniform.Offset;");
                        }
                        sb.AppendLine("}");
                        sb.AppendLine("return -1;");
                    }
                    sb.AppendLine("}");
                }
                sb.AppendLine("}");

                context.AddSource($"{effectName}.g.cs", sb.ToString());
            }
            catch (Exception ex)
            {
                sb.AppendLine(ex.ToString());
                
                context.AddSource($"{effectName}.g.cs", sb.ToString());
            }
        });
    }
}