using SoftFloat;

namespace NFMWorld.Util;

// https://stackoverflow.com/a/2147782
public class Random(long seed)
{
    private ulong seed = ((ulong)seed ^ 0x5DEECE66DUL) & ((1UL << 48) - 1);

    public int NextInt(int n)
    {
        if (n <= 0) throw new ArgumentException("n must be positive");

        if ((n & -n) == n)  // i.e., n is a power of 2
            return (int)((n * Next(31)) >> 31);

        long bits, val;
        do
        {
            bits = Next(31);
            val = bits % (uint) n;
        }
        while (bits - val + (n - 1) < 0);

        return (int) val;
    }

    private uint Next(int bits)
    {
        seed = (seed * 0x5DEECE66DL + 0xBL) & ((1L << 48) - 1);

        return (uint)(seed >> (48 - bits));
    }

    public double NextDouble() // Generated by ChatGPT
    {
        return (((long) Next(26) << 27) + Next(27)) / (double) (1L << 53);
    }

    public static double Double()
    {
        return System.Random.Shared.NextDouble();
    }

    public static float Single()
    {
        return System.Random.Shared.NextSingle();
    }

    public static bool Boolean()
    {
        return System.Random.Shared.NextSingle() >= 0.5f;
    }

    public static int Int(int minInclusive, int maxExclusive)
    {
        return System.Random.Shared.Next(minInclusive, maxExclusive);
    }
}