<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NFMWorld.Lua\NFMWorld.Lua.csproj"/>
        <ProjectReference Include="..\NFMWorld.LuaSourceGenerator\NFMWorld.LuaSourceGenerator.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>

    <!-- LuaCATS definition file output -->
    <ItemGroup>
        <CompilerVisibleProperty Include="LuaSourceGenerator_LuaCATSOutputDirectory"/>
        <CompilerVisibleProperty Include="LuaVisibleGenerator_StubsOutputDirectory"/>
    </ItemGroup>
    <PropertyGroup>
        <LuaSourceGenerator_LuaCATSOutputDirectory>$(MSBuildProjectDirectory)\..\NFMWorld.Library\data\library\declarations</LuaSourceGenerator_LuaCATSOutputDirectory>
        <LuaVisibleGenerator_StubsOutputDirectory>$(MSBuildProjectDirectory)\..\NFMWorld.Library\data\library\declarations</LuaVisibleGenerator_StubsOutputDirectory>
    </PropertyGroup>

</Project>
