using System.Text;

namespace NFMWorld.ShaderCompiler;

/// <summary>
/// Emits the C# bundle: one class per program, holding the per-backend sources and the
/// merged reflection, in the same spirit as sokol-shdc's
/// <c>generators/sokolc.cc</c>.
///
/// The emitted shape follows NFMWorld's existing FnaShaderIncrementalGenerator: a static
/// factory returning the module(s) plus a <c>Bind(...)</c> helper that resolves this
/// program's reflected slots against the pipeline's reflection.
/// </summary>
public static class CSharpBundleEmitter
{
    private sealed class IndentedStringBuilder
    {
        private readonly StringBuilder _sb = new();
        private int _indent;

        public IDisposable Indent()
        {
            _indent++;
            return new Popper(this);
        }

        private sealed class Popper(IndentedStringBuilder owner) : IDisposable
        {
            public void Dispose() => owner._indent--;
        }

        public void Line(string text = "")
        {
            if (text.Length == 0) { _sb.Append('\n'); return; }
            _sb.Append(' ', _indent * 4).Append(text).Append('\n');
        }

        /// <summary>
        /// Appends a line at column 0, ignoring the current indent. Needed for multi-line raw
        /// string literals, whose content and closing delimiter must both start at column 0.
        /// </summary>
        public void LineRaw(string text) => _sb.Append(text).Append('\n');

        public override string ToString() => _sb.ToString();
    }

    /// <summary>ShaderStage.Fragment is named "Pixel" in the emitted API, matching IShaderModule's vocabulary.</summary>
    private static string MemberName(ShaderStage stage) => stage == ShaderStage.Vertex ? "Vertex" : "Pixel";

    public static string Emit(ProgramReflection program, IReadOnlyDictionary<ShaderStage, StageSources> sourcesByStage)
    {
        var sb = new IndentedStringBuilder();
        var name = program.Name;

        sb.Line("// <auto-generated/>");
        sb.Line("// Generated by the shader compiler. Do not edit.");
        sb.Line("#nullable enable");
        sb.Line();
        sb.Line("using System;");
        sb.Line("using System.Collections.Generic;");
        sb.Line("using NFMWorld.Shaders;");
        sb.Line();
        // The namespace the app's consumers already import (Effects.cs, AbstractionNvgRenderer.cs,
        // SdlImGuiRenderer.cs), and the same one the FNA generator emitted into - so replacing one
        // with the other does not touch a call site's usings. The parameter wrappers this file
        // names unqualified (`Float4x4EffectParameter` and friends) live in the enclosing NFMWorld
        // namespace, which C# searches without a using.
        sb.Line("namespace NFMWorld.Shaders.Generated;");
        sb.Line();
        sb.Line($"internal static class {name}");
        sb.Line("{");
        using (sb.Indent())
        {
            EmitSources(sb, program.Stages, sourcesByStage);
            EmitCreate(sb, name, program);
        }
        sb.Line("}");
        sb.Line();

        // Beside the class rather than nested inside it, matching the FNA generator this replaces:
        // every consumer already names these types unqualified (`LineBasicParameters`, not
        // `LineBasic.LineBasicParameters`), because that is the shape they were written against.
        EmitParameters(sb, name, program);

        return sb.ToString();
    }

    /// <summary>
    /// Emits every backend's form of every stage. The spirv-cross output is embedded verbatim:
    /// the stage entry points are all named <c>main</c> by the time it is produced, so nothing
    /// here has to know the source's original entry-point names.
    /// </summary>
    private static void EmitSources(
        IndentedStringBuilder sb,
        IReadOnlyList<StageReflection> stages,
        IReadOnlyDictionary<ShaderStage, StageSources> sourcesByStage)
    {
        foreach (var stage in stages)
        {
            if (!sourcesByStage.TryGetValue(stage.Stage, out var sources))
                continue;

            var member = MemberName(stage.Stage);
            sb.Line($"/// <summary>SPIR-V for the {stage.Stage} stage (entry point <c>{stage.EntryPoint}</c>).</summary>");
            sb.Line($"private static ReadOnlyMemory<byte> {member}Spirv => new byte[]");
            sb.Line("{");
            using (sb.Indent())
            {
                var bytes = sources.Spirv;
                for (var i = 0; i < bytes.Length; i += 16)
                    sb.Line(string.Join(", ", bytes.Skip(i).Take(16).Select(b => "0x" + b.ToString("x2"))) + ",");
            }
            sb.Line("};");
            sb.Line();

            EmitSource(sb, $"{member}Hlsl", "HLSL, compiled by sokol's D3D11 backend", sources.Hlsl);
            EmitSource(sb, $"{member}Msl", "Metal Shading Language, compiled by sokol's Metal backend", sources.Msl);
            EmitSource(sb, $"{member}Glsl", "GLSL, compiled by sokol's GL backend", sources.Glsl);
            EmitSource(sb, $"{member}GlslEs", "OpenGL ES 3.0 GLSL, compiled by a GLES3 context or ANGLE", sources.GlslEs);
            EmitSource(sb, $"{member}Glsl330", "Desktop GLSL 3.30, compiled by a core-profile desktop GL context", sources.Glsl330);
        }
    }

    private static void EmitSource(IndentedStringBuilder sb, string member, string what, string text)
    {
        sb.Line($"/// <summary>{what}.</summary>");
        sb.Line($"private const string {member} =");
        // A raw string literal so the source's own quotes and backslashes need no escaping. The
        // delimiters have to sit at column 0 with the content, because a multi-line raw string
        // closes on its own line and every content line must be indented at least as far as the
        // closing delimiter - and the compiler's output is written at column 0 to begin with.
        sb.LineRaw("\"\"\"");
        sb.LineRaw(text.TrimEnd('\n'));
        sb.LineRaw("\"\"\";");
        sb.Line();
    }

    private static void EmitCreate(IndentedStringBuilder sb, string name, ProgramReflection program)
    {
        sb.Line("/// <summary>");
        sb.Line("/// Builds this program's modules and reflection. The reflection is parsed once here,");
        sb.Line("/// not re-derived from source at runtime.");
        sb.Line("/// </summary>");
        sb.Line($"public static {name}Program Create() => new(");
        using (sb.Indent())
        {
            foreach (var stage in program.Stages)
            {
                var member = MemberName(stage.Stage);
                sb.Line($"new ShaderStageSources(");
                using (sb.Indent())
                {
                    sb.Line($"{member}Spirv,");
                    sb.Line($"{member}Hlsl,");
                    sb.Line($"{member}Msl,");
                    sb.Line($"{member}Glsl,");
                    sb.Line($"{member}GlslEs,");
                    sb.Line($"{member}Glsl330),");
                }
            }
            EmitReflection(sb, program);
        }
        sb.Line(");");
    }

    private static void EmitReflection(IndentedStringBuilder sb, ProgramReflection program)
    {
        sb.Line("new ShaderReflection");
        sb.Line("{");
        using (sb.Indent())
        {
            sb.Line("Uniforms = new UniformParam[]");
            sb.Line("{");
            using (sb.Indent())
            {
                foreach (var block in program.UniformBlocks)
                    foreach (var member in block.Members)
                        sb.Line($"new(\"{member.Name}\", {member.Offset}, {member.SizeBytes}, UniformType.{MapUniformType(member)}),");
            }
            sb.Line("},");

            sb.Line("Textures = new ResourceBinding[]");
            sb.Line("{");
            using (sb.Indent())
            {
                foreach (var t in program.Textures)
                    sb.Line($"new(\"{t.Name}\", {t.Slot}),");
            }
            sb.Line("},");

            sb.Line("Samplers = new ResourceBinding[]");
            sb.Line("{");
            using (sb.Indent())
            {
                foreach (var s in program.Samplers)
                    sb.Line($"new(\"{s.Name}\", {s.Slot}),");
            }
            sb.Line("},");
        }
        // No trailing comma: this closes the last argument of Create()'s constructor call.
        sb.Line("}");
    }

    private static string MapUniformType(UniformMember member) => (member.Type, member.Columns, member.VectorSize) switch
    {
        (BaseType.Float, > 1, _) => "Matrix4x4",
        (BaseType.Float, _, 4) => "Vector4",
        (BaseType.Float, _, 3) => "Vector3",
        (BaseType.Float, _, 2) => "Vector2",
        (BaseType.Float, _, _) => "Float",
        // Bool shares the Int arm: a bool uniform occupies a 4-byte int in the block, which is what
        // UniformType describes, and what BoolEffectParameter writes. See HlslBoolUniforms for why
        // the reflection can carry Bool at all when SPIR-V cannot.
        (BaseType.Int or BaseType.Uint or BaseType.Bool, _, _) => "Int",
        _ => "Float",
    };

    /// <summary>
    /// The parameter wrapper type for a uniform member, as <c>Mad/Renderer/Shaders/Parameters.cs</c>
    /// names it.
    ///
    /// The wrapper is what a caller actually holds - <c>p.transformMat.SetValue(cb, ...)</c> - so
    /// the emitted member has to carry one rather than the bare slot index. That file already
    /// takes a plain <c>int</c> slot and writes at byte-offset semantics, which is what the GL
    /// backend's <c>SetUniform</c> expects, so nothing there needs to change to serve this
    /// compiler's output.
    /// </summary>
    private static string WrapperType(UniformMember member) => (member.Type, member.Columns, member.VectorSize) switch
    {
        (BaseType.Float, > 1, _) => "Float4x4EffectParameter",
        (BaseType.Float, _, 4) => "Float4EffectParameter",
        (BaseType.Float, _, 3) => "Float3EffectParameter",
        (BaseType.Float, _, 2) => "Float2EffectParameter",
        (BaseType.Float, _, _) => "FloatEffectParameter",
        (BaseType.Int, _, 4) => "Int4EffectParameter",
        (BaseType.Int, _, 3) => "Int3EffectParameter",
        (BaseType.Int, _, 2) => "Int2EffectParameter",
        (BaseType.Int, _, _) => "IntEffectParameter",
        (BaseType.Uint, _, 4) => "Uint4EffectParameter",
        (BaseType.Uint, _, 3) => "Uint3EffectParameter",
        (BaseType.Uint, _, 2) => "Uint2EffectParameter",
        (BaseType.Uint, _, _) => "UintEffectParameter",
        (BaseType.Bool, _, _) => "BoolEffectParameter",
        _ => "FloatEffectParameter",
    };

    private static void EmitParameters(IndentedStringBuilder sb, string name, ProgramReflection program)
    {
        sb.Line();
        sb.Line("/// <summary>");
        sb.Line("/// Resolves this program's uniform and texture slots against its own reflection.");
        sb.Line("/// Call once when the program is created - not per frame or per draw - and reuse the");
        sb.Line("/// result, since slots are stable for the program's lifetime.");
        sb.Line("/// </summary>");
        sb.Line($"internal readonly struct {name}Parameters");
        sb.Line("{");
        using (sb.Indent())
        {
            sb.Line($"internal {name}Parameters(ShaderReflection reflection)");
            sb.Line("{");
            using (sb.Indent())
            {
                foreach (var block in program.UniformBlocks)
                    foreach (var member in block.Members)
                        sb.Line($"{member.Name} = new {WrapperType(member)}(SlotOf(reflection, \"{member.Name}\"));");

                // Textures resolve against reflection.Textures, which is its own slot space -
                // matching what GlCommandBuffer.SetShaderResource indexes with.
                foreach (var texture in program.Textures)
                    sb.Line($"{texture.Name} = new TextureEffectParameter(TextureSlotOf(reflection, \"{texture.Name}\"));");
            }
            sb.Line("}");
            sb.Line();

            foreach (var block in program.UniformBlocks)
                foreach (var member in block.Members)
                    sb.Line($"public {WrapperType(member)} {member.Name} {{ get; }}");

            foreach (var texture in program.Textures)
                sb.Line($"public TextureEffectParameter {texture.Name} {{ get; }}");

            sb.Line();
            sb.Line("// -1 (\"not found\") mirrors the old FNA model's \"parameter != null\" check for a");
            sb.Line("// uniform the HLSL compiler optimized out - every *EffectParameter.SetValue below");
            sb.Line("// no-ops on a negative slot.");
            sb.Line("private static int SlotOf(ShaderReflection reflection, string name)");
            sb.Line("{");
            using (sb.Indent())
            {
                sb.Line("foreach (var uniform in reflection.Uniforms)");
                sb.Line("{");
                using (sb.Indent()) sb.Line("if (uniform.Name == name) return uniform.Offset;");
                sb.Line("}");
                sb.Line("return -1;");
            }
            sb.Line("}");
            sb.Line();
            sb.Line("private static int TextureSlotOf(ShaderReflection reflection, string name)");
            sb.Line("{");
            using (sb.Indent())
            {
                sb.Line("foreach (var texture in reflection.Textures)");
                sb.Line("{");
                using (sb.Indent()) sb.Line("if (texture.Name == name) return texture.Slot;");
                sb.Line("}");
                sb.Line("return -1;");
            }
            sb.Line("}");
        }
        sb.Line("}");
        sb.Line();
        sb.Line($"internal sealed record {name}Program(");
        using (sb.Indent())
        {
            foreach (var stage in program.Stages)
                sb.Line($"ShaderStageSources {MemberName(stage.Stage)},");
            sb.Line("ShaderReflection Reflection)");
        }
        sb.Line("{");
        using (sb.Indent())
        {
            foreach (var stage in program.Stages)
                sb.Line($"public ReadOnlyMemory<byte> {MemberName(stage.Stage)}Spirv => {MemberName(stage.Stage)}.Spirv;");
            sb.Line();
            sb.Line($"public {name}Parameters Bind() => new(Reflection);");
        }
        sb.Line("}");
    }
}
